"""Shared computational core for the Emission-Gap producer scripts.

Source paper: papers/2026-06-emission-gap/emission_gap_paper.tex
    "The Emission-Gap Theorem: No Salem Number in the Spectral Image,
     and the Cost Floor It Forces" (AceTheDactyl / Echo S Studios).

This module is a clean, self-contained re-implementation of the paper's
computational primitives (roots, Mahler measure, trace-down R(x)=x^m T(x+1/x),
the Salem flip-straddle decision, field / trace-form signatures, companion
matrices, and the self-action ad_M).  It is written to be imported by the
PRODUCER scripts in this folder; it deliberately does NOT import from, and is
independent of, the verifier suite in tests/2026-06-emission-gap/.

Precision policy (matches the paper's "exact arithmetic" banner):
  * transcendental / root magnitudes: mpmath at >= 40 decimal places;
  * every structural Salem decision (palindromy, flip-straddle root counting,
    field / trace-form signatures) is exact via sympy factorisation and Sturm
    root counting -- no floating point crosses a decision branch.
"""
from __future__ import annotations

import csv
import json
import os

import mpmath as mp
import numpy as np
import sympy as sp

mp.mp.dps = 50

# sympy symbols used throughout
x, t = sp.symbols("x t")

# ---------------------------------------------------------------------------
# provenance + emission helpers  (every data file self-identifies its source)
# ---------------------------------------------------------------------------

SOURCE_PAPER = "papers/2026-06-emission-gap/emission_gap_paper.tex"
FOLDER = "2026-06-emission-gap"


def data_dir() -> str:
    """Absolute path of data/2026-06-emission-gap/, created if missing."""
    here = os.path.dirname(os.path.abspath(__file__))
    repo = os.path.abspath(os.path.join(here, "..", ".."))
    d = os.path.join(repo, "data", FOLDER)
    os.makedirs(d, exist_ok=True)
    return d


def write_csv(filename: str, fieldnames, rows, script: str) -> str:
    """Write rows (list of dicts) to a CSV with a provenance comment header."""
    path = os.path.join(data_dir(), filename)
    with open(path, "w", newline="", encoding="utf-8") as f:
        f.write(f"# source: {SOURCE_PAPER}; generated by: code/{FOLDER}/{script}\n")
        w = csv.DictWriter(f, fieldnames=fieldnames)
        w.writeheader()
        for r in rows:
            w.writerow(r)
    return path


def _json_default(o):
    """Coerce sympy / numpy / mpmath scalars to native JSON types."""
    if isinstance(o, (np.integer,)):
        return int(o)
    if isinstance(o, (np.floating,)):
        return float(o)
    if isinstance(o, sp.Integer):
        return int(o)
    if isinstance(o, (sp.Rational, sp.Float, mp.mpf)):
        return float(o)
    return str(o)


def write_json(filename: str, payload: dict, script: str) -> str:
    """Write a JSON object carrying _source_paper / _generated_by provenance."""
    path = os.path.join(data_dir(), filename)
    out = {"_source_paper": SOURCE_PAPER, "_generated_by": f"code/{FOLDER}/{script}"}
    out.update(payload)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(out, f, indent=2, default=_json_default)
        f.write("\n")
    return path


def s(val, digits: int = 30) -> str:
    """Decimal string of an mpmath value to `digits` significant figures."""
    return mp.nstr(mp.mpf(val), digits, strip_zeros=False)


# ---------------------------------------------------------------------------
# roots / Mahler measure  (Sec. 1; Def. 2.3; Cor. 6.1)
# ---------------------------------------------------------------------------

def mp_roots(coeffs):
    """High-precision roots of a polynomial, coefficients highest-degree-first."""
    cc = [c if isinstance(c, mp.mpc) else mp.mpf(str(c)) for c in coeffs]
    return mp.polyroots(cc, maxsteps=2000, extraprec=400)


def mahler(coeffs) -> mp.mpf:
    """Mahler measure  M(p) = |a_n| * prod_i max(1, |alpha_i|)  (highest-first)."""
    cc = [mp.mpf(str(c)) for c in coeffs]
    lead = abs(cc[0])
    prod = mp.mpf(1)
    for r in mp.polyroots(cc, maxsteps=2000, extraprec=400):
        m = abs(r)
        if m > 1:
            prod *= m
    return lead * prod


def arg_degrees(z) -> float:
    """Argument of a complex number in degrees, in [0, 360)."""
    ang = mp.degrees(mp.atan2(z.imag, z.real))
    return float(ang % 360)


# ---------------------------------------------------------------------------
# sympy plumbing
# ---------------------------------------------------------------------------

def as_poly(obj, var=x) -> sp.Poly:
    if isinstance(obj, sp.Poly):
        return obj
    if isinstance(obj, (list, tuple)):
        return sp.Poly(list(obj), var)
    return sp.Poly(obj, var)


def is_palindromic(coeffs) -> bool:
    """Self-reciprocal (palindromic) integer coefficient list, highest-first."""
    c = [sp.nsimplify(v) for v in coeffs]
    return c == c[::-1]


# ---------------------------------------------------------------------------
# trace-down  R(x) = x^m T(x + 1/x)  and the Salem flip-straddle  (Sec. 8)
# ---------------------------------------------------------------------------

def trace_down(Rpoly) -> sp.Poly:
    """Trace-down polynomial T(t) of a monic self-reciprocal R of even degree 2m.

    Uses the Chebyshev-type recurrence  x^k + x^{-k} = c_k(t)  with
    c_0 = 2, c_1 = t, c_{k+1} = t c_k - c_{k-1}, so that R(x) = x^m T(x + 1/x).
    (Def. 8.1 / Lemma 8.2.)
    """
    R = as_poly(Rpoly)
    deg = R.degree()
    assert deg % 2 == 0, "trace-down requires even degree"
    m = deg // 2
    a = list(reversed(R.all_coeffs()))          # a[k] = coeff of x^k
    c = [sp.Integer(2), t]                       # c_0, c_1
    for k in range(1, m):
        c.append(sp.expand(t * c[k] - c[k - 1]))
    T = sp.sympify(a[m])
    for k in range(1, m + 1):
        T += a[m + k] * c[k]
    return sp.Poly(sp.expand(T), t)


def flip_straddle(Tpoly) -> bool:
    """Salem flip-straddle (Lemma 8.2): T totally real with exactly one root in
    (2, inf) and the remaining m-1 roots in (-2, 2)."""
    T = as_poly(Tpoly, t)
    m = T.degree()
    if T.eval(2) == 0 or T.eval(-2) == 0:        # a root on the flip => not Salem
        return False
    if T.count_roots() != m:                     # not totally real
        return False
    n_out = T.count_roots(sp.Integer(2), None)   # roots in [2, +inf]
    n_in = T.count_roots(sp.Integer(-2), sp.Integer(2))
    return n_out == 1 and n_in == m - 1


# ---------------------------------------------------------------------------
# Salem detection (the paper's exact guard: palindromy + flip-straddle)
# ---------------------------------------------------------------------------

def salem_factors(poly):
    """Irreducible integer factors of `poly` that are Salem polynomials, decided
    exactly via monic palindromy + trace-down flip-straddle (Thm. 8.3 guard)."""
    P = as_poly(poly)
    out = []
    for fac, _mult in sp.factor_list(P.as_expr(), x)[1]:
        Q = sp.Poly(fac, x)
        d = Q.degree()
        if d < 4 or d % 2:
            continue
        coeffs = Q.all_coeffs()
        if coeffs[0] == -1:                       # normalise sign
            coeffs = [-cc for cc in coeffs]
            Q = sp.Poly(coeffs, x)
        if coeffs[0] != 1:                         # Salem numbers are integers
            continue
        if not is_palindromic(coeffs):
            continue
        if flip_straddle(trace_down(Q)):
            out.append(Q)
    return out


def has_salem_factor(poly) -> bool:
    return len(salem_factors(poly)) > 0


def is_salem_numeric(coeffs, tol=1e-9) -> bool:
    """Numeric Salem test from root geometry: one root outside the unit disk,
    one inside, the rest on the circle, dominant root real > 1 (highest-first)."""
    deg = len(coeffs) - 1
    if deg < 4 or deg % 2:
        return False
    rts = np.roots([complex(c) for c in coeffs])
    mods = np.abs(rts)
    outside = int(np.sum(mods > 1 + tol))
    inside = int(np.sum(mods < 1 - tol))
    oncirc = int(np.sum(np.abs(mods - 1) <= tol))
    if outside != 1 or inside != 1 or oncirc < 2:
        return False
    beta = rts[int(np.argmax(mods))]
    return abs(beta.imag) <= tol and beta.real > 1


# ---------------------------------------------------------------------------
# field signatures & the trace form  (Sec. 9, 10)
# ---------------------------------------------------------------------------

def signature_from_minpoly(coeffs):
    """(r1, r2) of Q(theta) from an irreducible minimal polynomial (highest-first):
    r1 = number of real roots, r2 = number of complex-conjugate pairs."""
    P = sp.Poly(coeffs, x)
    r1 = int(P.count_roots())
    r2 = (P.degree() - r1) // 2
    return (r1, r2)


def field_signature(gen_expr):
    """((r1, r2), degree) of Q(gen_expr) via its exact minimal polynomial."""
    P = sp.Poly(sp.minimal_polynomial(gen_expr, x), x)
    r1 = int(P.count_roots())
    r2 = (P.degree() - r1) // 2
    return (r1, r2), int(P.degree())


def power_sums(coeffs, K):
    """Newton's identities: power sums p_0..p_K of the roots of a monic integer
    polynomial (highest-first, leading coefficient 1). Exact rationals."""
    c = [sp.Rational(v) for v in coeffs]
    assert c[0] == 1, "power_sums needs a monic polynomial"
    n = len(c) - 1
    cs = c[1:]                                    # cs[i-1] = coeff of x^{n-i}
    p = [sp.Integer(n)]                           # p_0 = n
    for k in range(1, K + 1):
        if k <= n:
            acc = sum(cs[i - 1] * p[k - i] for i in range(1, k))
            p.append(-acc - k * cs[k - 1])
        else:
            acc = sum(cs[i - 1] * p[k - i] for i in range(1, n + 1))
            p.append(-acc)
    return p


def trace_form_signature(coeffs):
    """Signature (n_pos, n_neg) of the trace form Tr_{K/Q}(z^2) on Q(theta).

    Builds the exact-integer Gram matrix G_{ij} = Tr(theta^{i+j}) = p_{i+j} from
    Newton power sums, then counts positive / negative eigenvalues EXACTLY via
    Sturm root counting on its (integer) characteristic polynomial -- an exact
    inertia computation rather than a floating eigenvalue solve. (Prop. 9.1.)
    """
    n = sp.Poly(coeffs, x).degree()
    p = power_sums(coeffs, 2 * n - 2)
    G = sp.Matrix(n, n, lambda i, j: p[i + j])
    lam = sp.symbols("lam")
    chi = sp.Poly(G.charpoly(lam).as_expr(), lam)
    # multiplicity of the zero eigenvalue = number of trailing zero coefficients
    mult0 = 0
    for cc in reversed(chi.all_coeffs()):
        if cc == 0:
            mult0 += 1
        else:
            break
    pos = chi.count_roots(sp.Integer(0), None) - mult0     # roots in (0, +inf)
    neg = chi.count_roots(None, sp.Integer(0)) - mult0     # roots in (-inf, 0)
    return int(pos), int(neg)


# ---------------------------------------------------------------------------
# companions & self-action ad_M  (Sec. 10)
# ---------------------------------------------------------------------------

def companion(coeffs):
    """Companion matrix (float numpy) of a monic polynomial, highest-first."""
    P = sp.Poly(coeffs, x)
    assert P.LC() == 1
    c = [float(v) for v in P.all_coeffs()]        # [1, c1, ..., cn]
    n = P.degree()
    M = np.zeros((n, n))
    M[1:, :-1] = np.eye(n - 1)
    M[:, -1] = [-c[n - k] for k in range(n)]      # last column: -c_n,...,-c_1
    return M


def companion_int(coeffs):
    """Integer companion matrix as a sympy Matrix (for exact charpoly work)."""
    return sp.Matrix(companion(coeffs).astype(int).tolist())


def ad_operator(M):
    """Matrix of the self-action ad_M : X -> M X - X M on matrix space, via the
    Kronecker identity  ad_M = M (x) I - I (x) M^T  (Def. 10.1 / Lemma 10.2)."""
    n = M.shape[0]
    I = np.eye(n)
    return np.kron(M, I) - np.kron(I, M.T)


# the emission catalog (Def. 2.1): seed -> stated minimal polynomial, highest-first
CATALOG = {
    "phi":   [1, -1, -1],       # x^2 - x - 1     golden ratio
    "tau":   [1, 1, -1],        # x^2 + x - 1     golden conjugate seed
    "sqrt2": [1, 0, -2],        # x^2 - 2
    "sqrt3": [1, 0, -3],        # x^2 - 3
    "sqrt5": [1, 0, -5],        # x^2 - 5
    "gap":   [1, -7, 1],        # x^2 - 7x + 1    ( = phi^4 )
    "K":     [1, 0, 5, 0, -5],  # x^4 + 5x^2 - 5  (the one Lorentzian generator)
}

# the Lehmer polynomial (smallest known Salem number), highest-first
LEHMER = [1, 1, 0, -1, -1, -1, -1, -1, 0, 1, 1]
