#!/usr/bin/env python3
"""
fc_probe.py -- the free-commutator door (Lehmer's Box; W-Sec 5.2, C-Finding 4.23).
BOUNDED PROBE: [computed] evidence at n in {4, 6, 8}. The door theorem at
UNBOUNDED n is NOT claimed; that remains the named internal theorem.

The door question: does the associative algebra generated by the catalog's
tensor/direct-sum images contain a full matrix algebra M_n?
  Over Q the cleanest certificate is dimensional:  dim_Q A = n^2  <=>  A = M_n(Q)
  (no Burnside/closed-field subtlety needed).
If full at n:
  * the commutator span is sl_n (dim n^2 - 1, all traces 0);
  * Albert--Muckenhoupt [established, 1957: over any field, every trace-zero
    matrix is a commutator [A,B]] applies WITH A, B inside the algebra;
  * hence the trace-zero Salem witness  W6 = C(beta4) (+) C(x^2+x+1)
    (charpoly = (x^4-x^3-x^2-x+1)(x^2+x+1), trace 1 + (-1) = 0)
    IS a commutator of catalog-algebra elements: the door provably emits a
    minimal-Salem-quartet-containing spectrum at that size.
Controls:
  * in-context commutator = ad_R on M_2: spectrum {0,0,+sqrt5,-sqrt5}
    (the CLOSED entry, W-Prop Sylvester, Sec 4) -- replicated;
  * same-splitting (+)-generators stay reducible (dim <= 20 < 36): the door's
    hinge is the MISMATCH of splittings, exhibited.
Exact arithmetic: integer matrices, Fraction Gaussian elimination.
"""
import sys
from fractions import Fraction
from sympy import Matrix, symbols, factor, sqrt, expand, Poly

x = symbols('x')
PASS, FAIL = [], []
def check(cid, cond, note=""):
    ok = bool(cond)
    (PASS if ok else FAIL).append(cid)
    print(f"[{'PASS' if ok else 'FAIL'}] {cid:8s} {note}")
    return ok

# ---------------- integer-matrix toolkit ----------------
def matmul(A, B):
    n, m, p = len(A), len(B), len(B[0])
    return [[sum(A[i][k]*B[k][j] for k in range(m)) for j in range(p)] for i in range(n)]

def kron(A, B):
    na, nb = len(A), len(B)
    return [[A[i//nb][j//nb]*B[i%nb][j%nb] for j in range(na*nb)] for i in range(na*nb)]

def blkdiag(*Ms):
    n = sum(len(M) for M in Ms)
    out = [[0]*n for _ in range(n)]
    off = 0
    for M in Ms:
        for i in range(len(M)):
            for j in range(len(M)):
                out[off+i][off+j] = M[i][j]
        off += len(M)
    return out

def flat(M): return [Fraction(v) for row in M for v in row]

def add_vec(basis, v):
    """basis: dict pivot -> normalized row; returns True iff v enlarges the span."""
    v = list(v)
    while True:
        piv = next((i for i, val in enumerate(v) if val != 0), None)
        if piv is None:
            return False
        if piv in basis:
            c = v[piv]; row = basis[piv]
            v = [a - c*b for a, b in zip(v, row)]
        else:
            c = v[piv]; basis[piv] = [a/c for a in v]
            return True

def algebra(gens, n):
    """Span of all words in gens (unital). Returns (dim, representative matrices)."""
    Id = [[1 if i == j else 0 for j in range(n)] for i in range(n)]
    basis, reps = {}, []
    add_vec(basis, flat(Id)); reps.append(Id)
    frontier = [Id]
    while frontier:
        new = []
        for B in frontier:
            for G in gens:
                for P in (matmul(B, G), matmul(G, B)):
                    if add_vec(basis, flat(P)):
                        reps.append(P); new.append(P)
        frontier = new
    return len(basis), reps

def commutator_span(reps, n):
    basis, dim, all_traceless = {}, 0, True
    for i in range(len(reps)):
        for j in range(i+1, len(reps)):
            C = [[a - b for a, b in zip(r1, r2)]
                 for r1, r2 in zip(matmul(reps[i], reps[j]), matmul(reps[j], reps[i]))]
            if sum(C[t][t] for t in range(n)) != 0:
                all_traceless = False
            add_vec(basis, flat(C))
    return len(basis), all_traceless

# ---------------- catalog seeds (companion matrices, all integer) ----------------
Rphi  = [[0, 1], [1, 1]]                          # x^2 - x - 1
Cs2   = [[0, 2], [1, 0]]                          # x^2 - 2
Cs3   = [[0, 3], [1, 0]]                          # x^2 - 3
Cs5   = [[0, 5], [1, 0]]                          # x^2 - 5
Cgap  = [[0, -1], [1, 7]]                         # x^2 - 7x + 1
CK    = [[0, 0, 0, 5], [1, 0, 0, 0], [0, 1, 0, -5], [0, 0, 1, 0]]     # x^4 + 5x^2 - 5
Cbeta4= [[0, 0, 0, -1], [1, 0, 0, 1], [0, 1, 0, 1], [0, 0, 1, 1]]     # x^4 - x^3 - x^2 - x + 1
Ceis  = [[0, -1], [1, -1]]                        # x^2 + x + 1

print("== fc_probe.py : free-commutator door, bounded Burnside/Wedderburn probe [computed] ==\n")

# ---------------- control 1: the in-context commutator ad_R is CLOSED ----------------
E = lambda i, j: Matrix(2, 2, lambda a, b: 1 if (a, b) == (i, j) else 0)
R = Matrix(Rphi)
cols = []
for (i, j) in ((0, 0), (0, 1), (1, 0), (1, 1)):
    C = R*E(i, j) - E(i, j)*R
    cols.append([C[0, 0], C[0, 1], C[1, 0], C[1, 1]])
adR = Matrix(4, 4, lambda a, b: cols[b][a])
cp = factor(adR.charpoly(x).as_expr())
check("FC-C1", cp == x**2*(x**2 - 5),
      f"ad_R on M_2: charpoly = x^2 (x^2 - 5) -> spectrum {{0,0,+-sqrt5}} (closed entry, W-Prop Sylvester Sec 4)")

# ---------------- control 2: same-splitting generators stay reducible ----------------
dim_red, _ = algebra([blkdiag(Rphi, CK), blkdiag(Cgap, CK)], 6)
check("FC-C2", dim_red <= 20,
      f"same-splitting (2+4,2+4) generators: dim = {dim_red} <= 20 = dim(M2 (+) M4) -- REDUCIBLE;"
      " the door's hinge is the mismatch of splittings")

# ---------------- the probe: n = 4, 6, 8 ----------------
dims = {}
gens4 = [kron(Rphi, Cs2), CK, kron(Cs3, Cgap)]
dims[4], reps4 = algebra(gens4, 4)
check("FC-P1", dims[4] == 16,
      f"n=4: dim <R_phi(x)C_sqrt2, C_K, C_sqrt3(x)C_gap> = {dims[4]} = 16 -> FULL M_4(Q)")
cdim4, tl4 = commutator_span(reps4, 4)
check("FC-P2", cdim4 == 15 and tl4,
      f"n=4: commutator span dim = {cdim4} = 15 = dim sl_4, all commutators trace-zero")

gens6 = [blkdiag(Rphi, CK), blkdiag(CK, Cs2), blkdiag(Cs2, Cs3, Cgap)]
dims[6], reps6 = algebra(gens6, 6)
check("FC-P3", dims[6] == 36,
      f"n=6: dim <mismatched (+)-images (2+4, 4+2, 2+2+2)> = {dims[6]} = 36 -> FULL M_6(Q)")
cdim6, tl6 = commutator_span(reps6, 6)
check("FC-P4", cdim6 == 35 and tl6,
      f"n=6: commutator span dim = {cdim6} = 35 = dim sl_6, all commutators trace-zero")

gens8 = [kron(Rphi, kron(Cs2, Cs3)), kron(Cgap, CK), kron(CK, Cs5)]
dims[8], reps8 = algebra(gens8, 8)
check("FC-P5", dims[8] == 64,
      f"n=8: dim <tensor images 2x2x2, 2x4, 4x2> = {dims[8]} = 64 -> FULL M_8(Q)")
cdim8, tl8 = commutator_span(reps8, 8)
check("FC-P6", cdim8 == 63 and tl8,
      f"n=8: commutator span dim = {cdim8} = 63 = dim sl_8, all commutators trace-zero")

# ---------------- the Salem witness at n = 6 ----------------
W6 = blkdiag(Cbeta4, Ceis)
trW = sum(W6[i][i] for i in range(6))
cpW = factor(Matrix(W6).charpoly(x).as_expr())
salem = Poly(x**4 - x**3 - x**2 - x + 1, x)
divides = Poly(Matrix(W6).charpoly(x).as_expr(), x).rem(salem) == Poly(0, x)
check("FC-W1", trW == 0,
      "witness W6 = C(beta4) (+) C(x^2+x+1): trace = 1 + (-1) = 0")
check("FC-W2", cpW == (x**4 - x**3 - x**2 - x + 1)*(x**2 + x + 1) and divides,
      "witness charpoly = (Salem quartic)(x^2+x+1): spectrum CONTAINS the full beta4 quartet")
check("FC-W3", dims[6] == 36,
      "Albert--Muckenhoupt chain: trace-zero + algebra = M_6(Q) => W6 = [A,B], A,B IN the algebra")

# ---------------- verdict ----------------
print(f"\ndims: n=4 -> {dims[4]}/16, n=6 -> {dims[6]}/36, n=8 -> {dims[8]}/64; "
      f"same-splitting control -> {dim_red}/36")
print("VERDICT [computed, bounded]: at every probed size with mismatched splittings the")
print("catalog algebra is FULL, its commutator span is sl_n, and at n=6 the door provably")
print("emits a spectrum containing the minimal Salem quartet (via Albert--Muckenhoupt).")
print("Extrapolation supports the NEGATIVE closure horn of the door item -- 'the door is")
print("provably a door, the Emission-Gap's scope (W-Thm 5.1) final' -- but the unbounded-n irreducibility")
print("theorem remains the named internal target; nothing here settles it.")
print(f"\nFC: EXACT {len(PASS)}/{len(PASS)+len(FAIL)} checks passed | "
      f"{'exit 0' if not FAIL else 'exit 1'}")
sys.exit(0 if not FAIL else 1)
