#!/usr/bin/env python3
# fc_unbounded_check.py -- the free-commutator door at UNBOUNDED size (second lane).
#
# TARGET (v2.7 find:gapdichotomy + blk table): "does the associative algebra
# generated by the tensor/oplus-images of the catalog contain a full matrix
# algebra?" -- fc_probe answered [computed] at n=4,6,8; the unbounded-n theorem
# was NOT claimed.  This harness machine-checks every ingredient of the session
# report's induction proof, which claims it at every even n.
#
# THEOREM FC-1 (session report).  Let W_n be the size-n tensor/oplus words over
# the catalog seeds (companions of x^2-x-1, x^2+x-1, x^2-2, x^2-3, x^2-5,
# x^2-7x+1; and of the K-seed x^4+5x^2-5).  Then
#   (i)   word sizes are exactly the even integers n >= 2;
#   (ii)  A_n := Q-algebra generated by W_n equals M_n(Q) for every even n;
#   (iii) [A_n, A_n] spans sl_n(Q);
#   (iv)  no trace-zero QUARTIC Salem matrix exists (pairing obstruction), so
#         the minimal Salem-carrying commutator size is 6, where
#         W = C_{s4} (+) diag(-1,0), s4 = x^4-x^3-x^2-x+1 (minimal quartic
#         Salem, trace-down t^2-t-3, guards 9 < 13 < 25), is an EXACT
#         commutator [A,B] with A,B in A_6 = M_6(Q) (Fillmore hollow +
#         distinct-diagonal solve); padding W (+) 0 reaches every even n >= 6.
#
# RANK CERTIFICATES (exactness note): every rank here is computed mod the
# Mersenne prime p = 2^61-1.  rank_Q >= rank_p always (specialization can only
# drop rank), so rank_p = n^2 certifies rank_Q = n^2 EXACTLY; for commutator
# spans, trace(AB-BA) = 0 gives the a-priori upper bound rank_Q <= n^2-1, so
# rank_p = n^2-1 certifies rank_Q = n^2-1 EXACTLY.  No float enters anywhere;
# polynomial decisions use sympy exact arithmetic (Sturm counts, resultants).
#
# CHECK GROUPS: FC-A sizes/seeds; FC-B base; FC-C direct spans n=4,6;
# FC-D induction ingredients n=6,8,10 (+ direct n=8, n=10); FC-E sl_n;
# FC-F no trace-zero quartic Salem; FC-G witness certification;
# FC-H explicit exact commutator + padding.  LF endings.  Exit 0.

import sys, itertools, random
from fractions import Fraction
import sympy as sp
from sympy import Symbol, Rational, Poly, sqrt, simplify, oo

x = Symbol('x'); y = Symbol('y')
PASS = 0; FAIL = 0
P = (1 << 61) - 1  # Mersenne prime

def check(cid, desc, ok):
    global PASS, FAIL
    tag = "PASS" if ok else "FAIL"
    if ok: PASS += 1
    else: FAIL += 1
    print(f"[{tag}] {cid}: {desc}")

random.seed(6)

# ---------------------------------------------------------------- int-matrix toolkit
def mat_mul(A, B):
    n = len(A); m = len(B[0]); k = len(B)
    Bt = list(zip(*B))
    return [tuple(sum(A[i][t]*Bt[j][t] for t in range(k)) for j in range(m)) for i in range(n)]

def mat_sub(A, B):
    return [tuple(a - b for a, b in zip(ra, rb)) for ra, rb in zip(A, B)]

def dsum(*blocks):
    n = sum(len(b) for b in blocks)
    M = [[0]*n for _ in range(n)]
    off = 0
    for b in blocks:
        s = len(b)
        for i in range(s):
            for j in range(s):
                M[off+i][off+j] = b[i][j]
        off += s
    return [tuple(r) for r in M]

def kron(A, B):
    na, nb = len(A), len(B)
    n = na*nb
    M = [[0]*n for _ in range(n)]
    for i in range(na):
        for j in range(na):
            for k_ in range(nb):
                for l in range(nb):
                    M[i*nb + k_][j*nb + l] = A[i][j]*B[k_][l]
    return [tuple(r) for r in M]

def flat(M):
    return [e for row in M for e in row]

class ModRank:
    """Incremental row-echelon rank mod P."""
    def __init__(self, dim):
        self.piv = {}   # col -> normalized row (list mod P)
        self.dim = dim
    def insert(self, vec):
        v = [e % P for e in vec]
        for c in sorted(self.piv):
            if v[c]:
                coef = v[c]
                pr = self.piv[c]
                v = [(a - coef*b) % P for a, b in zip(v, pr)]
        lead = next((i for i, e in enumerate(v) if e), None)
        if lead is None:
            return False
        inv = pow(v[lead], P - 2, P)
        self.piv[lead] = [(e*inv) % P for e in v]
        return True
    @property
    def rank(self):
        return len(self.piv)

# ---------------------------------------------------------------- seeds
def companion(coeffs):
    d = len(coeffs)
    M = [[0]*d for _ in range(d)]
    for i in range(1, d):
        M[i][i-1] = 1
    for i in range(d):
        M[i][d-1] = -coeffs[d-1-i]
    return [tuple(r) for r in M]

C_phi  = companion([-1, -1])
C_tau  = companion([1, -1])
C_s2   = companion([0, -2])
C_s3   = companion([0, -3])
C_s5   = companion([0, -5])
C_gap  = companion([-7, 1])
C_K    = companion([0, 5, 0, -5])
SEEDS2 = [C_phi, C_tau, C_s2, C_s3, C_s5, C_gap]
BLOCKS4 = [C_K] + [kron(a, b) for a, b in itertools.product(SEEDS2, SEEDS2)]

seed_polys = [x**2-x-1, x**2+x-1, x**2-2, x**2-3, x**2-5, x**2-7*x+1, x**4+5*x**2-5]
ok_seed = True
for m, p in zip(SEEDS2 + [C_K], seed_polys):
    cp = sp.Matrix(m).charpoly(x).as_expr()
    if sp.expand(cp - p) != 0:
        ok_seed = False
check("FC-A1", "seed companions realize the seven catalog seed polynomials exactly (char-poly identity)", ok_seed)

def attainable_sizes(limit=30):
    sizes = {2, 4}
    changed = True
    while changed:
        changed = False
        for a in sorted(sizes):
            for b in sorted(sizes):
                for s in (a + b, a * b):
                    if s <= limit and s not in sizes:
                        sizes.add(s); changed = True
    return sizes
check("FC-A2", "attainable word sizes <= 30 are exactly the even integers >= 2 (BFS over {+,x} from {2,4}); parity closure makes odd sizes unreachable at every bound",
      attainable_sizes(30) == set(range(2, 31, 2)))

# ---------------------------------------------------------------- word sampler
def parts(n):
    if n == 0:
        yield []
    if n >= 2:
        for rest in parts(n - 2):
            yield [2] + rest
    if n >= 4:
        for rest in parts(n - 4):
            yield [4] + rest

def words_of_size(n, count):
    plist = list(parts(n))
    out = []
    for _ in range(count):
        pp = random.choice(plist)
        blocks = [random.choice(SEEDS2) if s == 2 else random.choice(BLOCKS4) for s in pp]
        out.append(dsum(*blocks))
    return out

def algebra_rank(n, nwords=60, budget=1500):
    """rank_p of the algebra generated by size-n words; returns (rank, certified_full)."""
    mr = ModRank(n*n)
    pool = words_of_size(n, nwords)
    for w_ in pool:
        mr.insert(flat(w_))
    tries = 0
    while mr.rank < n*n and tries < budget:
        A = random.choice(pool); B = random.choice(pool)
        C = mat_mul(A, B)
        if mr.insert(flat(C)):
            pool.append(C)
        tries += 1
    return mr.rank

# ---------------------------------------------------------------- FC-B / FC-C: base and direct spans
r2 = algebra_rank(2, nwords=6)
check("FC-B1", f"A_2 = M_2(Q): rank_p = {r2} = 4 certifies rank_Q = 4 (mod-p rank is a lower bound; 4 is the ceiling)", r2 == 4)
r4 = algebra_rank(4, nwords=60)
check("FC-C1", f"A_4 = M_4(Q): rank_p = {r4} = 16 (exact certificate)", r4 == 16)
r6 = algebra_rank(6, nwords=90)
check("FC-C2", f"A_6 = M_6(Q): rank_p = {r6} = 36 (independent fc_probe replication, exact certificate)", r6 == 36)

# ---------------------------------------------------------------- FC-D: induction ingredients at n = 6, 8, 10
def zero_block(M, r0, r1, c0, c1):
    return all(M[i][j] == 0 for i in range(r0, r1) for j in range(c0, c1))

def induction_ingredients(n):
    m = n - 2
    # shared tail Y of size m
    tailblocks = []
    left = m
    while left >= 4:
        tailblocks.append(C_K); left -= 4
    while left >= 2:
        tailblocks.append(C_s3); left -= 2
    Y = dsum(*tailblocks)
    W1 = dsum(C_phi, Y); W2 = dsum(C_tau, Y)
    D = mat_sub(W1, W2)
    ing1 = (not zero_block(D, 0, 2, 0, 2)) and zero_block(D, 2, n, 0, n) and zero_block(D, 0, n, 2, n)
    # ING-2: corner flanking span{ (p (+) Y) D (q (+) Y) } restricted to the 2x2 corner = M_2
    mrc = ModRank(4)
    for p_ in SEEDS2:
        for q_ in SEEDS2:
            Pw = dsum(p_, Y); Qw = dsum(q_, Y)
            C = mat_mul(mat_mul(Pw, D), Qw)
            mrc.insert([C[0][0], C[0][1], C[1][0], C[1][1]])
    ing2 = mrc.rank == 4
    # ING-3: tail difference 0 (+) (Ya - Yb) with shared head
    if m == 4:
        Ya, Yb = C_K, kron(C_phi, C_s2)
    else:
        padc = [C_phi] * ((m - 4)//2)
        Ya = dsum(C_K, *padc)
        Yb = dsum(kron(C_phi, C_s2), *padc)
    Dt = mat_sub(dsum(C_s2, Ya), dsum(C_s2, Yb))
    ing3 = zero_block(Dt, 0, 2, 0, 2) and (not zero_block(Dt, 2, n, 2, n)) and zero_block(Dt, 0, 2, 2, n)
    # ING-4: mixer off-strips in the (2, n-2) partition
    if n == 4:
        G = kron(C_phi, C_s2)
    else:
        padl = []
        left = n - 4
        while left >= 2:
            padl.append(C_phi); left -= 2
        G = dsum(kron(C_phi, C_s2), *padl)
    ing4 = (not zero_block(G, 0, 2, 2, n)) and (not zero_block(G, 2, n, 0, 2))
    # ING-5: bimodule flanking of the top strip: span{E2 * G12 * Em} = full 2 x m
    G12 = [tuple(G[i][2:]) for i in range(2)]
    mrs = ModRank(2*m)
    for i in range(2):
        for j in range(2):
            for k_ in range(m):
                for l in range(m):
                    # E2(i,j) * G12 * Em(k,l): picks row j of G12 col k -> entry at (i,l)
                    val = G12[j][k_]
                    if val == 0:
                        continue
                    vec = [0]*(2*m)
                    vec[i*m + l] = val
                    mrs.insert(vec)
    ing5 = mrs.rank == 2*m
    return ing1, ing2, ing3, ing4, ing5

for n in (6, 8, 10):
    i1, i2, i3, i4, i5 = induction_ingredients(n)
    check(f"FC-D-{n}", f"induction ingredients at n={n}: diff-block, corner-flank rank 4, tail-diff, mixer off-strips, strip-flank rank {2*(n-2)} (the 4+(n-2)^2+4(n-2)=n^2 assembly dimension is verified directly by the rank certificates FC-D8b/FC-D10b, not by an arithmetic identity)",
          all((i1, i2, i3, i4, i5)))

r8 = algebra_rank(8, nwords=120, budget=2500)
check("FC-D8b", f"A_8 = M_8(Q): rank_p = {r8} = 64 (direct, corroborates the induction)", r8 == 64)
r10 = algebra_rank(10, nwords=150, budget=4000)
check("FC-D10b", f"A_10 = M_10(Q): rank_p = {r10} = 100 (direct, one size beyond fc_probe's window)", r10 == 100)

# ---------------------------------------------------------------- FC-E: commutator span = sl_n (exact sandwich)
def commutator_rank(n, nwords=70, budget=3000):
    pool = words_of_size(n, nwords)
    # enrich the pool with a few products so commutators can reach everything
    for _ in range(40):
        A = random.choice(pool); B = random.choice(pool)
        pool.append(mat_mul(A, B))
    mr = ModRank(n*n)
    tries = 0
    while mr.rank < n*n - 1 and tries < budget:
        A = random.choice(pool); B = random.choice(pool)
        C = mat_sub(mat_mul(A, B), mat_mul(B, A))
        mr.insert(flat(C))
        tries += 1
    return mr.rank

cr4 = commutator_rank(4)
cr6 = commutator_rank(6)
check("FC-E1", f"[A_4,A_4]: rank_p = {cr4} = 15; trace-zero bounds rank_Q <= 15, so rank_Q = 15 = dim sl_4 EXACTLY", cr4 == 15)
check("FC-E2", f"[A_6,A_6]: rank_p = {cr6} = 35 = dim sl_6 (same exact sandwich)", cr6 == 35)

# ---------------------------------------------------------------- FC-F: no trace-zero quartic Salem (forced)
a, b = sp.symbols('a b')
pal = x**4 + a*x**3 + b*x**2 + a*x + 1
check("FC-F1", "palindromic quartic with zero trace is EVEN: p|_{a=0}(x) = p|_{a=0}(-x) => roots +-paired => two off-circle roots => never Salem (symbolic identity)",
      sp.expand(pal.subs(a, 0) - pal.subs(a, 0).subs(x, -x)) == 0)

def is_salem_quartic(av, bv):
    p = Poly(x**4 + av*x**3 + bv*x**2 + av*x + 1, x)
    if not p.is_irreducible:
        return False
    q = Poly([1, av, bv - 2], y)   # y^2 + a y + (b-2), y = x + 1/x
    rr = sp.real_roots(q)
    if len(rr) != 2:
        return False
    y1, y2 = sorted(rr)
    return (y2 > 2 and -2 < y1 < 2) or (y1 < -2 and -2 < y2 < 2)

salems = [(av, bv) for av in range(-10, 11) for bv in range(-10, 11) if is_salem_quartic(av, bv)]
check("FC-F2", f"scan |a|,|b|<=10: {len(salems)} quartic Salem minimal polynomials found, every one has trace -a != 0 (0 violations)",
      len(salems) > 0 and all(av != 0 for av, bv in salems))

# ---------------------------------------------------------------- FC-G: the n=6 Salem witness, exact certification
s4 = x**4 - x**3 - x**2 - x + 1
Ps4 = Poly(s4, x)
check("FC-G1", "s4 = x^4-x^3-x^2-x+1 irreducible and palindromic (x^4 s4(1/x) = s4(x))",
      Ps4.is_irreducible and sp.expand(x**4 * s4.subs(x, Rational(1)/x) - s4) == 0)
check("FC-G2", "trace-down exact: s4 = x^2 ((x+1/x)^2 - (x+1/x) - 3); T(t) = t^2 - t - 3",
      sp.simplify(s4 - sp.expand(x**2 * ((x + 1/x)**2 - (x + 1/x) - 3))) == 0)
check("FC-G3", "Salem guards: y1 = (1+sqrt13)/2 > 2 iff 13 > 9; y2 = (1-sqrt13)/2 in (-2,2) iff 13 < 25; both integer decisions",
      simplify(((1+sqrt(13))/2)**2 - (1+sqrt(13))/2 - 3) == 0 and 13 > 9 and 13 < 25)
check("FC-G4", "beta_4 in (17/10, 2), unique root beyond 17/10's mirror: Sturm counts at rational endpoints",
      Ps4.count_roots(Rational(17, 10), 2) == 1 and Ps4.count_roots(2, oo) == 0)
check("FC-G5", "on-circle pair certified: x^2 - y2 x + 1 has product 1 and discriminant y2^2 - 4 < 0 (exact)",
      simplify(((1 - sqrt(13))/2)**2 - 4) < 0)

Wtop = companion([-1, -1, -1, 1])
Wint = dsum(Wtop, [(-1, 0), (0, 0)])
Wm = sp.Matrix(Wint)
check("FC-G6", "witness W = C_{s4} (+) diag(-1,0): trace 0 and char poly = s4 * x * (x+1) exactly",
      Wm.trace() == 0 and sp.expand(Wm.charpoly(x).as_expr() - sp.expand(s4*x*(x+1))) == 0)

# ---------------------------------------------------------------- FC-H: explicit exact [A,B] = W over Q
def hollow_similarity(M):
    """M: sympy Rational matrix, trace 0. Returns S with (S^-1 M S) zero-diagonal, exact."""
    n = M.rows
    if n == 1:
        return sp.eye(1) if M[0, 0] == 0 else None
    # scalar => zero (trace 0)
    if M == M[0, 0] * sp.eye(n):
        return sp.eye(n) if M[0, 0] == 0 else None
    # find v among e_j, e_i + e_j with M v not parallel to v
    v = None
    cand = [sp.Matrix([[1 if r == j else 0] for r in range(n)]) for j in range(n)]
    for i in range(n):
        for j in range(i + 1, n):
            e = sp.zeros(n, 1); e[i, 0] = 1; e[j, 0] = 1
            cand.append(e)
    for e in cand:
        Me = M * e
        # parallel test: rank of [e | Me] < 2 ?
        if sp.Matrix.hstack(e, Me).rank() == 2:
            v = e; break
    if v is None:
        return None
    w_ = M * v
    cols = [v, w_]
    for j in range(n):
        e = sp.zeros(n, 1); e[j, 0] = 1
        if sp.Matrix.hstack(*cols, e).rank() == len(cols) + 1:
            cols.append(e)
        if len(cols) == n:
            break
    T = sp.Matrix.hstack(*cols)
    N = T.inv() * M * T
    assert N[0, 0] == 0
    C = N[1:, 1:]
    S2 = hollow_similarity(C)
    if S2 is None:
        return None
    Tf = sp.eye(n); Tf[1:, 1:] = S2
    return T * Tf

def exact_commutator(Wmat):
    n = Wmat.rows
    S = hollow_similarity(Wmat)
    if S is None:
        return None
    H = S.inv() * Wmat * S
    if any(H[i, i] != 0 for i in range(n)):
        return None
    Ad = sp.diag(*[Rational(i + 1) for i in range(n)])
    B0 = sp.zeros(n, n)
    for i in range(n):
        for j in range(n):
            if i != j:
                B0[i, j] = H[i, j] / (Ad[i, i] - Ad[j, j])
    if sp.simplify(Ad*B0 - B0*Ad - H) != sp.zeros(n, n):
        return None
    A = S * Ad * S.inv(); B = S * B0 * S.inv()
    if sp.simplify(A*B - B*A - Wmat) != sp.zeros(n, n):
        return None
    return A, B

res6 = exact_commutator(Wm)
check("FC-H1", "Fillmore hollow similarity exists over Q for W (constructive, exact)", res6 is not None)
if res6 is not None:
    A6, B6 = res6
    check("FC-H2", "[A,B] = W verified EXACTLY, A,B in M_6(Q) = A_6: the Salem quartet is a genuine catalog-algebra commutator spectrum",
          sp.simplify(A6*B6 - B6*A6 - Wm) == sp.zeros(6, 6))
    check("FC-H3", "denominator audit: A, B have explicit rational entries (finite heights); no float appeared anywhere in the construction",
          all(e.is_Rational for e in A6) and all(e.is_Rational for e in B6))
else:
    check("FC-H2", "skipped", False)
    check("FC-H3", "skipped", False)

W8 = sp.Matrix(dsum(Wint, [(0, 0), (0, 0)]))
res8 = exact_commutator(W8)
check("FC-H4", "padding: W (+) 0_2 at n=8 is again an exact commutator; spectrum still contains the Salem quartet (works at every even n >= 6 by the same construction)",
      res8 is not None)

print()
print(f"fc_unbounded_check: {PASS}/{PASS+FAIL} PASS")
sys.exit(0 if FAIL == 0 else 1)
