"""
Independent verification of Section 3 ("The self-coupling obstruction") of
"The Dissolved Helix and Its Orthogonal Partner".

Covers: Proposition 3.1 (Cayley-Hamilton collapse) eq. (3) [eq:phicollapse],
Lemma 3.2 (magnitude never returns to the floor, incl. S10),
Proposition 3.3 (charge sublattice {0,2} closed, {1,3} unreachable),
Proposition 3.4 (empty Salem slot) eq. (4) [eq:occupant],
Corollary 3.5 (no self-coupling) as an assembled sanity check.
"""
import sympy as sp
import mpmath as mp

mp.mp.dps = 50

sqrt5 = sp.sqrt(5)
phi = (1 + sqrt5) / 2
R = sp.Matrix([[0, 1], [1, 1]])
I2 = sp.eye(2)


# ---------------------------------------------------------------- Prop. 3.1
def test_characteristic_operator_collapse_eq3():
    """Eq. (3): Phi_R(R) = R^2 - Tr(R) R + det(R) I = R^2 - R - I = 0."""
    Phi = R**2 - sp.trace(R) * R + R.det() * I2
    assert sp.simplify(Phi - (R**2 - R - I2)) == sp.zeros(2, 2)
    assert Phi == sp.zeros(2, 2)


def test_self_bracket_vanishes():
    """Prop. 3.1: [R,R] = R^2 - R^2 = 0 (generative grade vanishes)."""
    bracket = R * R - R * R
    assert bracket == sp.zeros(2, 2)


# ---------------------------------------------------------------- Lemma 3.2
def test_mahler_oplus_doubles():
    """Lemma 3.2: Mah(A + A) = Mah(A)^2 (oplus concatenates -> Mah multiplies).
    For A_phi (Mah = phi): Mah(A_phi + A_phi) = phi^2."""
    mah_A = phi
    # A_phi (+) A_phi = {phi, psi, phi, psi}; Mahler = product of max(1,|.|)
    assert sp.simplify(mah_A * mah_A - phi**2) == 0


def test_mahler_adams_squares():
    """Lemma 3.2: Mah(psi^2 A) = Mah(A)^2 (Adams squaring squares each |lambda|)."""
    mah_A = phi
    assert sp.simplify(mah_A**2 - phi**2) == 0


def test_S10_floor_fixed_point():
    """Lemma 3.2 / S10: Mah(psi^2 A) = Mah(A)  iff  Mah(A) = 1.
    Instance 1: golden object Mah=phi != 1 -> phi^2 != phi.
    Instance 2: cyclotomic object {i,-i} Mah=1 -> squares give {-1,-1} Mah=1."""
    assert sp.simplify(phi**2 - phi) != 0            # phi>1: not a fixed point
    # a Mahler-1 object on the unit circle
    roots = [sp.I, -sp.I]
    mah = 1
    for r in roots:
        mah *= sp.Max(1, sp.Abs(r))
    assert mah == 1
    sq = [r**2 for r in roots]                       # {-1,-1}
    mah_sq = 1
    for r in sq:
        mah_sq *= sp.Max(1, sp.Abs(r))
    assert mah_sq == 1                               # fixed at Mah=1


def test_self_composites_never_reach_floor():
    """Lemma 3.2: every self-composite has Mah in {phi^2, phi^4, ...} > 1;
    the cyclotomic floor Mah=1 is never reached."""
    m = phi
    for _ in range(6):
        m = m**2                                      # iterate Adams squaring
        assert (m > 1) == True                        # noqa: E712
        assert sp.simplify(m - 1) != 0
    # closed form after k squarings of phi is phi^(2^k)
    assert sp.simplify(m - phi**(2**6)) == 0


# ---------------------------------------------------------------- Prop. 3.3
def test_charge_sublattice_closed():
    """Prop. 3.3: {0,2} closed under union, +mod4, and doubling; {1,3} unreachable.
    {0,2} u {0,2} = {0,2};  {0,2}+{0,2} mod4 = {0,2};  2*{0,2} mod4 = {0}."""
    S = {0, 2}
    assert S | S == {0, 2}
    plus = {(a + b) % 4 for a in S for b in S}
    assert plus == {0, 2}
    dbl = {(2 * a) % 4 for a in S}
    assert dbl == {0}
    # closure of the sub-semigroup generated by {0,2} under + never yields {1,3}
    gen = set(S)
    for _ in range(6):
        gen |= {(a + b) % 4 for a in gen for b in gen}
    assert gen == {0, 2}
    assert gen.isdisjoint({1, 3})


# ---------------------------------------------------------------- Prop. 3.4
def test_salem_on_circle_range():
    """Prop. 3.4: on |theta|=1, t = theta + theta^{-1} = 2 Re theta in [-2,2]."""
    alpha = sp.symbols('alpha', real=True)
    theta = sp.exp(sp.I * alpha)
    t = sp.simplify(theta + 1 / theta)
    assert sp.simplify(t - 2 * sp.cos(alpha)) == 0
    # 2 cos alpha ranges over [-2,2]
    for a in [0, sp.pi / 3, sp.pi / 2, sp.pi, 2 * sp.pi / 3]:
        val = float(2 * sp.cos(a))
        assert -2 <= val <= 2


def test_salem_expanding_identity():
    """Prop. 3.4: for real theta, t - 2 = (theta-1)^2/theta; hence t>2 for theta>1."""
    th = sp.symbols('theta', positive=True)
    lhs = (th + 1 / th) - 2
    rhs = (th - 1)**2 / th
    assert sp.simplify(lhs - rhs) == 0
    # strictly positive for theta>1  =>  disjoint from the [-2,2] circle band
    for tv in [sp.Rational(3, 2), sp.Integer(2), sp.Integer(5)]:
        assert (rhs.subs(th, tv) > 0) == True         # noqa: E712


def test_occupant_eq4():
    """Eq. (4): tau0 = beta + beta^{-1} > 2 > phi, and tau0 - 2 = (beta-1)^2/beta,
    with beta = sqrt((5+3 sqrt5)/2) (the K-formation imaginary radius)."""
    beta = sp.sqrt((5 + 3 * sqrt5) / 2)
    tau0 = beta + 1 / beta
    # identity (exact, AM-GM)
    assert sp.simplify((tau0 - 2) - (beta - 1)**2 / beta) == 0
    # ordering tau0 > 2 > phi, evaluated at high precision independently
    tb = mp.sqrt((5 + 3 * mp.sqrt(5)) / 2)
    tau0_num = tb + 1 / tb
    phi_num = (1 + mp.sqrt(5)) / 2
    assert tau0_num > 2 > phi_num
    assert tau0_num > mp.mpf('2.83') and tau0_num < mp.mpf('2.84')


# ---------------------------------------------------------------- Cor. 3.5
def test_no_self_coupling_assembly():
    """Cor. 3.5: closure needs the orthogonal phases {1,3}, which no self-op
    supplies: generative grade 0, phase pinned to {0,2}, Mahler away from 1."""
    assert (R * R - R * R) == sp.zeros(2, 2)          # generative grade zero
    reachable = {0, 2}
    for _ in range(4):
        reachable |= {(a + b) % 4 for a in reachable for b in reachable}
        reachable |= {(2 * a) % 4 for a in reachable}
    assert reachable == {0, 2}                        # never {1,3}
    assert sp.simplify(phi - 1) != 0                  # Mahler pinned above the floor
