"""The floor wall: the empty strip (1, phi).  Section 3 (Lemmas 3.1-3.2,
Remark 3.3).  We re-run the exhaustive quadratic scan and re-derive the
degree-two boundary cases and the operator-preservation arithmetic.
"""
import mpmath as mp
import sympy as sp

from _helpers import mahler_product

mp.mp.dps = 50
PHI = (1 + mp.sqrt(5)) / 2


def _mahler_quadratic(b, c):
    """Exact-enough Mahler measure of monic x^2 + b x + c (integers)."""
    disc = b * b - 4 * c
    if disc >= 0:
        sq = mp.sqrt(disc)
        r1 = (-b + sq) / 2
        r2 = (-b - sq) / 2
        return max(mp.mpf(1), abs(r1)) * max(mp.mpf(1), abs(r2))
    # complex-conjugate pair, both of modulus sqrt(c) (c > 0 here)
    return max(mp.mpf(1), mp.sqrt(c)) ** 2


def test_empty_quadratic_strip_scan():
    """Lemma 3.1 (P1-GATE-02/03): no monic integer quadratic with |b|,|c|<=12
    has Mahler measure in the open interval (1, phi); the paper reports 625
    quadratics scanned."""
    eps = mp.mpf(10) ** -30
    count = 0
    hits = []
    for b in range(-12, 13):
        for c in range(-12, 13):
            count += 1
            m = _mahler_quadratic(b, c)
            if 1 + eps < m < PHI - eps:
                hits.append((b, c, mp.nstr(m, 12)))
    assert count == 625
    assert hits == []            # the strip (1, phi) is empty


def test_quadratic_minimiser_is_phi_at_disc5():
    """Lemma 3.1: the minimal measure exceeding 1 is exactly phi, attained
    only by x^2-x-1 and x^2+x-1 (discriminant 5)."""
    eps = mp.mpf(10) ** -30
    best = None
    argmins = []
    for b in range(-12, 13):
        for c in range(-12, 13):
            m = _mahler_quadratic(b, c)
            if m > 1 + eps:
                if best is None or m < best - eps:
                    best = m
                    argmins = [(b, c)]
                elif abs(m - best) < eps:
                    argmins.append((b, c))
    assert abs(best - PHI) < mp.mpf(10) ** -25
    assert set(argmins) == {(-1, -1), (1, -1)}
    assert all(b * b - 4 * c == 5 for (b, c) in argmins)


def test_reciprocal_hyperbolic_case_formula():
    """Lemma 3.1, case c=-1: Mah = (|b| + sqrt(b^2+4))/2, increasing in |b|,
    minimised at |b|=1 giving phi = (1+sqrt5)/2."""
    for b in range(1, 20):
        expected = (b + mp.sqrt(b * b + 4)) / 2
        assert abs(_mahler_quadratic(b, -1) - expected) < mp.mpf(10) ** -30
    assert abs(_mahler_quadratic(1, -1) - PHI) < mp.mpf(10) ** -30
    # strictly increasing in |b|
    seq = [_mahler_quadratic(b, -1) for b in range(1, 20)]
    assert all(seq[i] < seq[i + 1] for i in range(len(seq) - 1))


def test_elliptic_case_c1_bge3_ge_phi_squared():
    """Lemma 3.1, case c=1, |b|>=3: dominant root >= (3+sqrt5)/2 = phi^2."""
    phi2 = PHI ** 2
    assert abs((3 + mp.sqrt(5)) / 2 - phi2) < mp.mpf(10) ** -30
    for b in range(3, 20):
        assert _mahler_quadratic(b, 1) >= phi2 - mp.mpf(10) ** -30


def test_operators_preserve_floor_arithmetic():
    """Lemma 3.2 / Remark 3.3: the semigroup generated by {phi,2,3,5,phi^4,beta^2}
    under multiplication (direct sum) and squaring stays in [phi, infinity); a
    product of two values in {1} U [phi, inf) stays there, and squaring a value
    > 1 lands >= phi^2.  No accumulation at 1."""
    phi = PHI
    beta2 = (5 + 3 * mp.sqrt(5)) / 2               # = 5.854..., the imag-root^2
    gens = [phi, mp.mpf(2), mp.mpf(3), mp.mpf(5), phi ** 4, beta2]
    # every generator is at or above the floor
    assert all(g >= phi - mp.mpf(10) ** -30 for g in gens)
    # closed under product: all pairwise products stay >= phi (indeed >= phi^2)
    for a in gens:
        for b in gens:
            assert a * b >= phi ** 2 - mp.mpf(10) ** -30
    # squaring an IMAGE value (which is > 1, hence >= phi) lands >= phi^2, so it
    # cannot fall into the forbidden strip (1, phi)
    for v in gens:
        assert v > 1
        assert v ** 2 >= phi ** 2 - mp.mpf(10) ** -30
    # a value in {1} U [phi,inf) times 1 stays there (identity of the semigroup)
    for g in gens:
        assert g * 1 == g


def test_gap_generator_is_phi_fourth():
    """Def. 2.9 / Remark 3.3: the 'gap' seed x^2-7x+1 has roots phi^4, phi^-4,
    so trace 7 and Mahler measure phi^4."""
    phi = PHI
    # phi^4 + phi^-4 = 7 and phi^4 * phi^-4 = 1
    assert abs(phi ** 4 + phi ** -4 - 7) < mp.mpf(10) ** -30
    assert abs(phi ** 4 * phi ** -4 - 1) < mp.mpf(10) ** -30
    assert abs(mahler_product([1, -7, 1]) - phi ** 4) < mp.mpf(10) ** -9
