r"""
Producer: descent of the composition laws (Section 4).

Source paper: papers/2026-07-relational-charge/relational_charge_paper.tex
Produces    : data/2026-07-relational-charge/descent_adams.csv
              data/2026-07-relational-charge/descent_tensor_crt.csv

Refactors Proposition 4.8 (Adams operations: psi^k multiplies every relative
charge by k, so Delta(psi^k O) = k Delta(O); the CRT/Adams projectors descend)
and Proposition 4.9 (Tensor: the lcm law Delta(A (x) B) = Z/lcm(m,k)Z on
admissible inputs; the CRT surjection Z/mZ x Z/kZ ->> Z/lcm(m,k)Z has kernel
cyclic of order gcd(m,k) generated by (m/d, -k/d); safe composition <=> coprime).

All relative charges are modelled exactly as elements of Q/Z.

Run: py code/2026-07-relational-charge/descent_laws.py
"""

import math
from fractions import Fraction

import sympy as sp

import relcharge_core as C
from relcharge_io import write_csv

x = C.x


def _order(diffset):
    L = 1
    for d in diffset:
        L = L * d.denominator // math.gcd(L, d.denominator)
    return L


def adams_rows():
    """Prop 4.8: on O = x^m-2 (angles j/m), psi^k sends t -> k t mod 1.
    Delta(psi^k O) = k Delta(O) = (1/(m/gcd(m,k)))Z/Z."""
    rows = []
    m = 6
    ang = [Fraction(j, m) for j in range(m)]
    diffs = {(a - b) % 1 for a in ang for b in ang}
    m0 = _order(diffs)
    for k in range(1, 9):
        ang_k = [(k * t) % 1 for t in ang]
        diffs_k = {(a - b) % 1 for a in ang_k for b in ang_k}
        mk = _order(diffs_k)
        scaled_ok = diffs_k == {(k * d) % 1 for d in diffs}
        rows.append({
            "base_object": "x^6-2",
            "base_relational_order_m": m0,
            "k": k,
            "psi_k_relational_order": mk,
            "predicted_m_over_gcd": m0 // math.gcd(m0, k),
            "matches_k_times_Delta": "yes" if (mk == m0 // math.gcd(m0, k)) else "no",
            "every_diff_is_k_times_original": "yes" if scaled_ok else "no",
        })
    # primary projectors for m = 12 = 2^2 * 3
    for pe in (4, 3):
        k = 12 // pe
        gen = Fraction(k, 12) % 1
        rows.append({
            "base_object": "Z/12 (m=2^2*3)",
            "base_relational_order_m": 12,
            "k": k,
            "psi_k_relational_order": gen.denominator,
            "predicted_m_over_gcd": pe,
            "matches_k_times_Delta": "yes" if gen.denominator == pe else "no",
            "every_diff_is_k_times_original": f"projects onto Z/{pe} (p-primary)",
        })
    return rows


def tensor_crt_rows():
    """Prop 4.9: lcm law + CRT kernel structure + safe<=>coprime."""
    rows = []
    pairs = [(2, 3), (4, 6), (3, 5), (6, 10), (4, 4), (12, 8), (9, 6),
             (5, 5), (10, 15)]
    for m, k in pairs:
        L = int(sp.ilcm(m, k))
        d = math.gcd(m, k)
        # subgroup (1/m)Z + (1/k)Z inside Q/Z
        combined = {(Fraction(a, m) + Fraction(b, k)) % 1
                    for a in range(m) for b in range(k)}
        target = {Fraction(j, L) % 1 for j in range(L)}
        lcm_ok = combined == target

        def surj(a, b):
            return (a * (L // m) + b * (L // k)) % L

        image = {surj(a, b) for a in range(m) for b in range(k)}
        kernel = [(a, b) for a in range(m) for b in range(k) if surj(a, b) == 0]
        # generator (m/d, -k/d)
        g = (m // d % m, (-(k // d)) % k)
        gen_sub, cur = set(), (0, 0)
        for _ in range(d):
            gen_sub.add(cur)
            cur = ((cur[0] + g[0]) % m, (cur[1] + g[1]) % k)
        rows.append({
            "m": m,
            "k": k,
            "lcm": L,
            "gcd": d,
            "Delta_tensor_order": _order({f for f in combined}),
            "lcm_law_holds": "yes" if (lcm_ok and _order(combined) == L) else "no",
            "crt_surjective": "yes" if image == set(range(L)) else "no",
            "kernel_order": len(kernel),
            "kernel_cyclic_gen_m_over_d_minus_k_over_d": "yes" if gen_sub == set(kernel) else "no",
            "safe_composition": "yes (coprime)" if d == 1 else "no",
            "coprime": "yes" if d == 1 else "no",
        })
    return rows


def main():
    a = adams_rows()
    fa = ["base_object", "base_relational_order_m", "k", "psi_k_relational_order",
          "predicted_m_over_gcd", "matches_k_times_Delta",
          "every_diff_is_k_times_original"]
    pa = write_csv("descent_adams.csv", fa, a, __file__)
    print(f"wrote {pa}  ({len(a)} Adams rows, Prop 4.8)")

    t = tensor_crt_rows()
    ft = ["m", "k", "lcm", "gcd", "Delta_tensor_order", "lcm_law_holds",
          "crt_surjective", "kernel_order",
          "kernel_cyclic_gen_m_over_d_minus_k_over_d", "safe_composition", "coprime"]
    pt = write_csv("descent_tensor_crt.csv", ft, t, __file__)
    print(f"wrote {pt}  ({len(t)} tensor/CRT rows, Prop 4.9)")


if __name__ == "__main__":
    main()
