"""
Shared helpers for the producer scripts of the paper

    "The Exchange Rate lambda = 2c: A Conformal Identity, Its Gate, and Its Flip"
    papers/2026-06-lambda-2c/lambda_2c_paper.tex

These are the reusable computational primitives (Mahler measures, companion
matrices, the Lie self-action ad_R, Fibonacci/Lucas sequences) plus provenance-
stamped CSV/JSON writers.  The producer scripts import these, compute a paper
result, and EMIT it to data/2026-06-lambda-2c/.  Nothing here asserts; the
independent assertions live in tests/2026-06-lambda-2c/ and are not imported.
"""
import os
import csv
import json
import numpy as np
import sympy as sp
import mpmath as mp

# ---------------------------------------------------------------------------
# Provenance / paths
# ---------------------------------------------------------------------------

SHORT = "2026-06-lambda-2c"
TEX = "lambda_2c_paper.tex"
SOURCE_PAPER = f"papers/{SHORT}/{TEX}"


def _repo_root():
    here = os.path.dirname(os.path.abspath(__file__))          # code/2026-06-lambda-2c
    return os.path.dirname(os.path.dirname(here))               # repo root


def data_dir():
    d = os.path.join(_repo_root(), "data", SHORT)
    os.makedirs(d, exist_ok=True)
    return d


def _generated_by(script):
    return f"code/{SHORT}/{script}"


def write_csv(filename, header, rows, script):
    """Write a CSV with the mandated provenance comment on line 1."""
    path = os.path.join(data_dir(), filename)
    with open(path, "w", newline="", encoding="utf-8") as f:
        f.write(f"# source: {SOURCE_PAPER}; generated by: {_generated_by(script)}\n")
        w = csv.writer(f)
        w.writerow(header)
        for row in rows:
            w.writerow(row)
    return path


def write_json(filename, obj, script):
    """Write a JSON object with the mandated provenance fields injected first."""
    path = os.path.join(data_dir(), filename)
    out = {"_source_paper": SOURCE_PAPER, "_generated_by": _generated_by(script)}
    out.update(obj)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(out, f, indent=2, ensure_ascii=False)
    return path


# ---------------------------------------------------------------------------
# Algebraic primitives
# ---------------------------------------------------------------------------

PHI = (1 + sp.sqrt(5)) / 2
PSI = (1 - sp.sqrt(5)) / 2


def companion(coeffs):
    """Companion matrix of the monic polynomial x^n + c_{n-1} x^{n-1} + ... + c_0
    given the low-to-high tail coefficients [c_0, ..., c_{n-1}].

    With this convention companion([-1, -1]) (i.e. x^2 - x - 1) is the golden
    keystone [[0, 1], [1, 1]].
    """
    n = len(coeffs)
    Cm = sp.zeros(n)
    for i in range(1, n):
        Cm[i, i - 1] = 1
    for i in range(n):
        Cm[i, n - 1] = -coeffs[i]
    return Cm


def ad_matrix(R):
    """4x4 matrix of the Lie self-action ad_R(X) = [R, X] = R X - X R on M_2(Q),
    expressed in the basis {E11, E12, E21, E22}.
    """
    basis = [sp.Matrix([[1, 0], [0, 0]]), sp.Matrix([[0, 1], [0, 0]]),
             sp.Matrix([[0, 0], [1, 0]]), sp.Matrix([[0, 0], [0, 1]])]
    cols = []
    for E in basis:
        adE = R * E - E * R
        cols.append([adE[0, 0], adE[0, 1], adE[1, 0], adE[1, 1]])
    return sp.Matrix(cols).T


def mahler_numpy(coeffs):
    """Mahler measure of a monic integer polynomial via numpy roots.
    coeffs are high-to-low (numpy convention), leading coefficient 1.
    """
    roots = np.roots(coeffs)
    M = 1.0
    for r in roots:
        if abs(r) > 1.0 + 1e-12:
            M *= abs(r)
    return M


def mahler_mpmath(coeffs, dps=45):
    """High-precision Mahler measure of a monic integer polynomial (mpmath).
    coeffs high-to-low; returns an mpmath real.
    """
    mp.mp.dps = dps
    roots = mp.polyroots(coeffs, maxsteps=400, extraprec=300)
    M = mp.mpf(1)
    for r in roots:
        if abs(r) > 1:
            M *= abs(r)
    return M.real


def fibonacci(n):
    """List [F_0, ..., F_n] with F_0 = 0, F_1 = 1."""
    F = [0, 1]
    while len(F) <= n:
        F.append(F[-1] + F[-2])
    return F[:n + 1]


def is_primitive(M, iters=40):
    """True iff some power of the non-negative matrix M (numpy) is strictly
    positive (Perron-Frobenius primitivity)."""
    P = M.copy()
    for _ in range(iters):
        if np.all(P > 0):
            return True
        P = P @ M
    return False


def poly_str(coeffs):
    """Render a monic integer polynomial from high-to-low coeff list, e.g.
    [1, -1, -1] -> 'x^2-x-1', [1, -7, 1] -> 'x^2-7x+1'."""
    n = len(coeffs) - 1
    terms = []
    for i, a in enumerate(coeffs):
        p = n - i
        if a == 0:
            continue
        sign = "+" if a > 0 else "-"
        mag = abs(a)
        if p == 0:
            body = f"{mag}"
        elif p == 1:
            body = f"{'' if mag == 1 else mag}x"
        else:
            body = f"{'' if mag == 1 else mag}x^{p}"
        terms.append(sign + body)
    out = "".join(terms)
    return out[1:] if out.startswith("+") else out


def exact(expr):
    """Human-readable exact form of a sympy expression for JSON storage."""
    return str(sp.simplify(expr))


def approx(expr, digits=15):
    """Float value of a sympy expression for JSON storage."""
    return float(sp.N(expr, digits + 3))
