r"""
rrl_core -- shared exact-arithmetic primitives for the producer scripts of

    "Residual Return: Exact Learning Dynamics and Language over the Vector
     Substrate" (papers/2026-06-residual-return-learning/residual_return_learning.tex)

This module is the *reusable* half of the code/ tree: companion matrices, the
trace-form Gram, the exact projector, the coordinates->minimal-polynomial bridge
implemented as the LARGEST INVARIANT FACTOR of the characteristic matrix (via
determinantal divisors over Q[x], exactly as Theorem 3.3 of the paper prescribes
-- not sympy's black-box minimal_polynomial that the independent tests use), the
Clifford matrix isomorphism, exact Mahler measure, and the SHA-256 witness link.

Everything is exact (sympy Rational / Integer); only Mahler measure and the
transcendental log-enclosures use mpmath, and never inside a decision.

NOT a test file: functions here COMPUTE and RETURN values; the producers call
them and EMIT machine-readable data to data/2026-06-residual-return-learning/.
"""
import json
import os
from itertools import combinations

import mpmath as mp
import sympy as sp
from sympy import Matrix, Rational as Q, eye, symbols, zeros

X = symbols("x")

# ---------------------------------------------------------------------------
# provenance / IO
# ---------------------------------------------------------------------------
SOURCE_PAPER = "papers/2026-06-residual-return-learning/residual_return_learning.tex"
_SHORT = "2026-06-residual-return-learning"


def data_dir():
    """Absolute path to this paper's data/ folder, resolved from __file__ so the
    producers write to the right place regardless of the current directory."""
    here = os.path.dirname(os.path.abspath(__file__))
    repo = os.path.dirname(os.path.dirname(here))  # code/<short>/ -> code -> repo
    d = os.path.join(repo, "data", _SHORT)
    os.makedirs(d, exist_ok=True)
    return d


def generated_by(script):
    return f"code/{_SHORT}/{script}"


def write_json(script, filename, payload):
    """Write JSON with provenance fields _source_paper and _generated_by first."""
    out = {"_source_paper": SOURCE_PAPER, "_generated_by": generated_by(script)}
    out.update(payload)
    path = os.path.join(data_dir(), filename)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(out, f, indent=2)
        f.write("\n")
    return path


def write_csv(script, filename, header, rows):
    """Write a CSV whose first line is the provenance comment the archive expects."""
    path = os.path.join(data_dir(), filename)
    with open(path, "w", encoding="utf-8", newline="") as f:
        f.write(f"# source: {SOURCE_PAPER}; generated by: {generated_by(script)}\n")
        f.write(",".join(str(h) for h in header) + "\n")
        for row in rows:
            f.write(",".join(str(v) for v in row) + "\n")
    return path


# ---------------------------------------------------------------------------
# polynomial / matrix helpers
# ---------------------------------------------------------------------------

def companion(coeffs):
    """Companion matrix of a monic poly coeffs=[1,c_{n-1},...,c_1,c_0].

    Coefficients sit in the last column; charpoly equals the given poly and
    trace(C**k) = sum(root_i**k) = Tr_{K/Q}(theta**k) for a primitive theta.
    Standard textbook (second) companion form.
    """
    n = len(coeffs) - 1
    C = zeros(n)
    for i in range(1, n):
        C[i, i - 1] = 1
    for i in range(n):
        C[i, n - 1] = -coeffs[n - i]
    return C


def trace_form_powerbasis(min_coeffs):
    """Exact trace-form Gram G_{ij}=Tr(theta^{i-1}theta^{j-1}) in the power basis,
    built from the regular representation (companion) of theta -- so the Gram is
    reconstructed from power sums, never transcribed."""
    C = companion(min_coeffs)
    n = C.shape[0]
    powers = [eye(n)]
    for _ in range(2 * n):
        powers.append(powers[-1] * C)
    p = [powers[k].trace() for k in range(2 * n)]
    return Matrix(n, n, lambda i, j: p[i + j])


def projector(B, G):
    """Exact G-orthogonal projector P = B (B^T G B)^{-1} B^T G onto col(B)."""
    return B * (B.T * G * B).inv() * B.T * G


def regular_rep(coords, min_coeffs):
    """Regular representation rho(alpha) of alpha = sum_i coords[i] theta^i on
    K = Q[x]/(m_theta), i.e. sum_i coords[i] C(m_theta)^i."""
    C = companion(min_coeffs)
    n = C.shape[0]
    rho = zeros(n)
    Cpow = eye(n)
    for a in coords:
        rho += a * Cpow
        Cpow = Cpow * C
    return rho


def _monic(poly, x=X):
    """Monic normalisation of a Q[x] polynomial expression (0 stays 0)."""
    poly = sp.expand(poly)
    if poly == 0:
        return sp.Integer(0)
    P = sp.Poly(poly, x)
    return sp.expand(P.as_expr() / P.LC())


def monic_gcd(polys, x=X):
    """Monic gcd of a list of Q[x] polynomials."""
    g = sp.Integer(0)
    for p in polys:
        g = sp.gcd(g, sp.expand(p))
    return _monic(g, x)


def determinantal_divisors(M, x=X):
    """D_0..D_n where D_k = monic gcd of all k-by-k minors of M (D_0 = 1)."""
    n = M.shape[0]
    D = [sp.Integer(1)]
    for k in range(1, n + 1):
        minors = [M.extract(list(rows), list(cols)).det()
                  for rows in combinations(range(n), k)
                  for cols in combinations(range(n), k)]
        D.append(monic_gcd(minors, x))
    return D


def invariant_factors(A, x=X):
    """Invariant factors f_1|f_2|...|f_n of A (from xI-A), each monic, via
    determinantal divisors f_k = D_k / D_{k-1}.  f_n is the minimal polynomial;
    prod(f_k) is the characteristic polynomial."""
    n = A.shape[0]
    M = x * eye(n) - A
    D = determinantal_divisors(M, x)
    return [sp.expand(sp.cancel(D[k] / D[k - 1])) for k in range(1, n + 1)]


def largest_invariant_factor(A, x=X):
    """Largest invariant factor of xI-A = minimal polynomial of A (Thm 3.3)."""
    return invariant_factors(A, x)[-1]


def coords_to_minpoly(coords, min_coeffs, x=X):
    """The paper's seed-naming bridge (Thm 3.3 / Ex 3.5): the minimal polynomial
    of alpha = sum coords[i] theta^i is the largest invariant factor of
    xI - rho(alpha).  Returns (minpoly_expr, is_algebraic_integer)."""
    A = regular_rep(coords, min_coeffs)
    mp_expr = largest_invariant_factor(A, x)
    P = sp.Poly(mp_expr, x)
    is_alg_int = all(c.is_Integer for c in P.all_coeffs())
    return mp_expr, is_alg_int


def poly_coeffs(expr, x=X):
    """Coefficient list [leading,...,constant] as ints where integral else strings."""
    P = sp.Poly(sp.expand(expr), x)
    out = []
    for c in P.all_coeffs():
        out.append(int(c) if c.is_Integer else str(c))
    return out


def poly_str(expr):
    return str(sp.expand(expr))


def mat_to_strlist(M):
    """2-D list of string entries (exact rationals preserved as 'p/q')."""
    return [[str(M[i, j]) for j in range(M.shape[1])] for i in range(M.shape[0])]


def mahler_measure(coeffs, dps=40):
    """Exact-to-<10^-30 Mahler measure of a monic integer polynomial given by
    coeffs=[1,...,c0]: product of max(1,|root|).  Returned as an mpf.
    maxsteps/extraprec are raised so multiple-root polynomials still converge."""
    mp.mp.dps = dps
    roots = mp.polyroots([mp.mpf(c) for c in coeffs],
                         maxsteps=200, extraprec=4 * dps)
    M = mp.mpf(1)
    for r in roots:
        M *= max(mp.mpf(1), abs(r))
    return M


def phi_mpf(dps=40):
    """The golden ratio as an mpf at the given precision."""
    mp.mp.dps = dps
    return (1 + mp.sqrt(5)) / 2


# ---------------------------------------------------------------------------
# Clifford Cl(2,0) = M_2(R) isomorphism
# ---------------------------------------------------------------------------

def mat(a, b, c, d):
    """Holding X = a + b e1 + c e2 + d i  ->  its 2x2 real matrix
    [[a+c, b-d],[b+d, a-c]]."""
    return Matrix([[a + c, b - d], [b + d, a - c]])


def cl_coords(M):
    """Inverse iso: 2x2 matrix -> (a,b,c,d) Clifford coordinates."""
    a = (M[0, 0] + M[1, 1]) / 2
    c = (M[0, 0] - M[1, 1]) / 2
    b = (M[1, 0] + M[0, 1]) / 2
    d = (M[1, 0] - M[0, 1]) / 2
    return (a, b, c, d)


KEYSTONE_R = mat(Q(1, 2), 1, Q(-1, 2), 0)  # R = 1/2 + e1 - 1/2 e2, mat = [[0,1],[1,1]]


def return_operator(Xmat, R=KEYSTONE_R):
    """The phi-keystone return operator L(X) = R X + X R - X (eq Lop)."""
    return R * Xmat + Xmat * R - Xmat


def return_operator_matrix(R=KEYSTONE_R):
    """4x4 matrix of L over the ordered Clifford basis {1,e1,e2,i}."""
    basis = [mat(1, 0, 0, 0), mat(0, 1, 0, 0), mat(0, 0, 1, 0), mat(0, 0, 0, 1)]
    cols = [list(cl_coords(return_operator(B, R))) for B in basis]
    return Matrix(cols).T


# ---------------------------------------------------------------------------
# SHA-256 witness chain (eq chain)
# ---------------------------------------------------------------------------

def witness_digest(prev_hash, body):
    """SHA-256(prev_hash || canonical-json(body))[0:16], the tamper-evident
    witness link of eq (chain).  canonical = sorted keys, no whitespace."""
    import hashlib
    canonical = json.dumps(body, sort_keys=True, separators=(",", ":"))
    digest = hashlib.sha256((prev_hash + canonical).encode()).hexdigest()[:16]
    return canonical, digest
