"""
box_io -- provenance-stamped output helpers for the Lehmer's Box producer
scripts.

Every data artifact self-identifies where it came from:
  * CSV  -> a leading comment line
        # source: papers/2026-06-lehmers-box/lehmers_box.tex; generated by: code/2026-06-lehmers-box/<script>.py
  * JSON -> top-level fields "_source_paper" and "_generated_by"

Source paper: papers/2026-06-lehmers-box/lehmers_box.tex
  "Lehmer's Box: A Golden Floor and an Angle Lattice that Confine Spectral
   Emission Away from Salem Numbers -- Without Resolving Lehmer's Problem"
  (AceTheDactyl / Echo S Studios Research Developments).

This module is a helper, not a producer; it is not run directly.
"""

from __future__ import annotations

import csv
import io
import json
import os

PAPER_TEX = "papers/2026-06-lehmers-box/lehmers_box.tex"
DATA_DIR = os.path.join(
    os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))),
    "data",
    "2026-06-lehmers-box",
)


def _script_rel(script_file: str) -> str:
    return "code/2026-06-lehmers-box/" + os.path.basename(script_file)


def data_path(name: str) -> str:
    os.makedirs(DATA_DIR, exist_ok=True)
    return os.path.join(DATA_DIR, name)


def write_csv(name: str, fieldnames, rows, script_file: str) -> str:
    """Write a CSV with a leading provenance comment then a header row."""
    path = data_path(name)
    buf = io.StringIO()
    buf.write(f"# source: {PAPER_TEX}; generated by: {_script_rel(script_file)}\n")
    w = csv.DictWriter(buf, fieldnames=list(fieldnames))
    w.writeheader()
    for r in rows:
        w.writerow(r)
    with open(path, "w", encoding="utf-8", newline="") as fh:
        fh.write(buf.getvalue())
    return path


def write_json(name: str, payload: dict, script_file: str) -> str:
    """Write a JSON object with provenance fields injected at the top."""
    path = data_path(name)
    out = {
        "_source_paper": PAPER_TEX,
        "_generated_by": _script_rel(script_file),
    }
    out.update(payload)
    with open(path, "w", encoding="utf-8") as fh:
        json.dump(out, fh, indent=2)
        fh.write("\n")
    return path
