"""
opalg_core -- shared producer toolkit for the whitepaper

    "The Operator Algebra of the Emission Semiring
     -- A lambda-Ring, the Adams Square, and Two Characters"
    (papers/2026-06-operator-algebra/operator-algebra-whitepaper.tex)

This module reimplements the paper's Definitions (Sec. 2-5) as a clean,
reusable library and is imported by the per-section PRODUCER scripts in this
folder.  Unlike the verifier suite in tests/ -- which asserts the laws over
generic symbols -- the producers here INSTANTIATE the laws on the concrete
seed catalogue and EMIT the computed values (measures, charges, multisets,
sequences) as machine-readable CSV/JSON.

Run directly, this script's main() emits
    data/2026-06-operator-algebra/seed_catalogue.csv
-- the seed eigenvalue catalogue with degree, Mahler measure, and charge --
the common input to every other producer.

Conventions (paper Definitions 2.1, 3.1, 4.1, 5.1):
    oplus   A (+) B  = multiset union                         (Def. 2.1)
    otimes  A (x) B  = { a*b : a in A, b in B }  (Kronecker)  (Def. 2.1)
    psi^n   psi^n(A) = { a**n : a in A }         (Adams op)   (Def. 3.1)
    M(A)             = prod_a max(1, |a|)                     (Def. 4.1)
    q(a)             = round(2*arg(a)/pi) mod 4  in Z/4Z      (Def. 5.1)
"""

from __future__ import annotations

import csv
import json
import os
from collections import Counter

import mpmath as mp
import sympy as sp

# --------------------------------------------------------------------------
# provenance / paths
# --------------------------------------------------------------------------
SHORT = "2026-06-operator-algebra"
SOURCE_PAPER = f"papers/{SHORT}/operator-algebra-whitepaper.tex"

_HERE = os.path.dirname(os.path.abspath(__file__))
_REPO_ROOT = os.path.dirname(os.path.dirname(_HERE))
DATA_DIR = os.path.join(_REPO_ROOT, "data", SHORT)


def _gen_by(script: str) -> str:
    return f"code/{SHORT}/{script}"


def data_path(name: str) -> str:
    os.makedirs(DATA_DIR, exist_ok=True)
    return os.path.join(DATA_DIR, name)


def write_csv(name: str, script: str, fieldnames, rows):
    """Write a CSV with a leading provenance comment line."""
    path = data_path(name)
    with open(path, "w", newline="", encoding="utf-8") as fh:
        fh.write(f"# source: {SOURCE_PAPER}; generated by: {_gen_by(script)}\n")
        w = csv.DictWriter(fh, fieldnames=list(fieldnames))
        w.writeheader()
        for r in rows:
            w.writerow(r)
    return path


def write_json(name: str, script: str, payload: dict):
    """Write JSON carrying _source_paper and _generated_by provenance fields."""
    path = data_path(name)
    out = {"_source_paper": SOURCE_PAPER, "_generated_by": _gen_by(script)}
    out.update(payload)
    with open(path, "w", encoding="utf-8") as fh:
        json.dump(out, fh, indent=2)
        fh.write("\n")
    return path


# --------------------------------------------------------------------------
# algebraic constants
# --------------------------------------------------------------------------
x = sp.Symbol("x")
I = sp.I
sqrt5 = sp.sqrt(5)
phi = (1 + sqrt5) / 2  # golden ratio, root of x^2 - x - 1


# --------------------------------------------------------------------------
# seeds (eigenvalue multisets) -- the paper's catalogue
# --------------------------------------------------------------------------
def seed_from_poly(poly_expr):
    """Eigenvalue multiset = roots (with multiplicity) of an integer poly."""
    rd = sp.roots(sp.Poly(poly_expr, x))
    out = []
    for r, m in rd.items():
        out.extend([r] * m)
    return tuple(out)


def golden_seed():
    """Roots of x^2 - x - 1 : {phi, 1 - phi}. Mahler measure phi (the floor)."""
    return (phi, 1 - phi)


def K_seed():
    """Lorentzian seed K = x^4 + 5 x^2 - 5; imaginary pair +- i*beta, M = beta^2."""
    return seed_from_poly(x**4 + 5 * x**2 - 5)


# Named catalogue used across the producers.  poly is a display string.
def seed_catalogue():
    """Ordered dict-like list of (name, poly_str, multiset) for the core seeds."""
    return [
        ("golden", "x^2 - x - 1", golden_seed()),
        ("x^2-2", "x^2 - 2", seed_from_poly(x**2 - 2)),
        ("x^2-3", "x^2 - 3", seed_from_poly(x**2 - 3)),
        ("x^2-5", "x^2 - 5", seed_from_poly(x**2 - 5)),
        ("K", "x^4 + 5x^2 - 5", K_seed()),
    ]


# --------------------------------------------------------------------------
# semiring / power operators (Def. 2.1, 3.1)
# --------------------------------------------------------------------------
ZERO = ()  # empty multiset  (additive identity)
ONE = (sp.Integer(1),)  # {1}  (multiplicative identity)


def oplus(A, B):
    """Direct sum = multiset union (Def. 2.1)."""
    return tuple(A) + tuple(B)


def otimes(A, B):
    """Tensor product = elementwise products with multiplicity (Def. 2.1)."""
    return tuple(sp.expand(sp.sympify(a) * sp.sympify(b)) for a in A for b in B)


def psi(n, A):
    """Adams / power operation lambda -> lambda**n (Def. 3.1)."""
    return tuple(sp.expand(sp.sympify(a) ** n) for a in A)


# --------------------------------------------------------------------------
# exact multiset equality
# --------------------------------------------------------------------------
def canon(A):
    return Counter(sp.expand(sp.sympify(a)) for a in A)


def ms_equal(A, B):
    return canon(A) == canon(B)


# --------------------------------------------------------------------------
# symmetric functions of an eigenvalue multiset
# --------------------------------------------------------------------------
def power_sum(A, k):
    """p_k = sum lambda_i**k."""
    return sp.expand(sum(sp.sympify(a) ** k for a in A))


def elem_sym(A, k):
    """e_k = k-th elementary symmetric polynomial of the multiset."""
    return sp.expand(sp.symmetric_poly(k, list(A)))


def sym2(A):
    """Sym^2 A = { lambda_i * lambda_j : i <= j } (Prop. 3.3)."""
    L = list(A)
    n = len(L)
    return tuple(sp.expand(L[i] * L[j]) for i in range(n) for j in range(i, n))


def wedge2(A):
    """Lambda^2 A = { lambda_i * lambda_j : i < j } (Prop. 3.3)."""
    L = list(A)
    n = len(L)
    return tuple(sp.expand(L[i] * L[j]) for i in range(n) for j in range(i + 1, n))


# --------------------------------------------------------------------------
# Character I : the Mahler measure (Def. 4.1)
# --------------------------------------------------------------------------
def mahler_exact(A):
    """M(A) = prod_a max(1, |a|), returned in exact closed form."""
    p = sp.Integer(1)
    for a in A:
        p *= sp.Max(1, sp.Abs(sp.sympify(a)))
    return sp.nsimplify(sp.radsimp(sp.simplify(p)))


def _to_mp_re_im(a, dps):
    a = sp.sympify(a)
    re = mp.mpf(str(sp.N(sp.re(a), dps + 15)))
    im = mp.mpf(str(sp.N(sp.im(a), dps + 15)))
    return re, im


def modulus_mp(a, dps=60):
    mp.mp.dps = dps
    re, im = _to_mp_re_im(a, dps)
    return mp.sqrt(re * re + im * im)


def mahler_mp(A, dps=60):
    """Numeric Mahler measure (independent cross-check of mahler_exact)."""
    mp.mp.dps = dps
    p = mp.mpf(1)
    for a in A:
        m = modulus_mp(a, dps)
        if m > 1:
            p *= m
    return p


def log_mahler_mp(A, dps=60):
    """log M(A) numerically = sum over |lambda|>1 of log|lambda|."""
    mp.mp.dps = dps
    s = mp.mpf(0)
    for a in A:
        m = modulus_mp(a, dps)
        if m > 1:
            s += mp.log(m)
    return s


def tropical_convolution(A, B, dps=60):
    """(max,+) convolution of the SEPARATE log-spectra (Thm 4.2, rhs):
        sum_{l in A} sum_{m in B} (log|l| + log|m|)^+ .
    Built only from |A| and |B|, never from the product object."""
    mp.mp.dps = dps
    s = mp.mpf(0)
    for a in A:
        la = mp.log(modulus_mp(a, dps))
        for b in B:
            lb = mp.log(modulus_mp(b, dps))
            s += max(mp.mpf(0), la + lb)
    return s


# --------------------------------------------------------------------------
# Character II : the angle charge (Def. 5.1)
# --------------------------------------------------------------------------
def charge_one(a, dps=60):
    """q = round(2 * arg(a) / pi) mod 4  in Z/4Z."""
    mp.mp.dps = dps
    re, im = _to_mp_re_im(a, dps)
    theta = mp.atan2(im, re)
    return int(mp.nint(2 * theta / mp.pi)) % 4


def charge(A, dps=60):
    """Multiset (Counter) of charges of an object."""
    return Counter(charge_one(a, dps) for a in A)


def sumset_mod4(cA, cB):
    """Sumset (mod 4) of two charge multisets: {qa + qb} with multiplicity."""
    out = Counter()
    for qa, na in cA.items():
        for qb, nb in cB.items():
            out[(qa + qb) % 4] += na * nb
    return out


# --------------------------------------------------------------------------
# emission / formatting helpers
# --------------------------------------------------------------------------
def exact_str(expr) -> str:
    """Human-readable exact string for a sympy expression."""
    return str(sp.nsimplify(sp.radsimp(sp.simplify(sp.sympify(expr)))))


def dec_str(expr, digits=30) -> str:
    """Fixed-precision decimal string for a (real) sympy expression."""
    return str(sp.N(sp.sympify(expr), digits))


def ms_str(A) -> str:
    """Canonical, sorted 'l1; l2; ...' string of a multiset for emission."""
    def key(a):
        a = sp.sympify(a)
        return (float(sp.re(a).evalf()), float(sp.im(a).evalf()))

    return "; ".join(str(sp.simplify(a)) for a in sorted(A, key=key))


def charge_multiset_str(c: Counter) -> str:
    """'q^mult' listing of a charge Counter, e.g. '0^2; 1^1; 2^1; 3^1'."""
    return "; ".join(f"{q}^{c[q]}" for q in sorted(c))


# --------------------------------------------------------------------------
# main() : emit the seed catalogue
# --------------------------------------------------------------------------
def main():
    rows = []
    for name, poly, seed in seed_catalogue():
        Mx = mahler_exact(seed)
        rows.append(
            {
                "seed": name,
                "polynomial": poly,
                "degree": len(seed),
                "eigenvalues": ms_str(seed),
                "mahler_exact": exact_str(Mx),
                "mahler_decimal": dec_str(Mx, 30),
                "charge_multiset": charge_multiset_str(charge(seed)),
            }
        )
    path = write_csv(
        "seed_catalogue.csv",
        "opalg_core.py",
        ["seed", "polynomial", "degree", "eigenvalues",
         "mahler_exact", "mahler_decimal", "charge_multiset"],
        rows,
    )
    print(f"wrote {path} ({len(rows)} seeds)")


if __name__ == "__main__":
    main()
