r"""Descent of the composition laws: Proposition 4.8 (Adams, prop:adams) and
Proposition 4.9 (Tensor / lcm law, prop:tensor).

Paper (Prop 4.8): psi^k multiplies every relative charge by k, so
Delta(psi^k O) = k Delta(O); and for Delta(O)=Z/mZ with m = prod p_i^{e_i},
psi^{m/p_i^{e_i}} projects onto the p_i-primary component.

Paper (Prop 4.9): for admissible A,B with groups Z/mZ, Z/kZ,
Delta(A (x) B) = (1/m)Z + (1/k)Z = (1/lcm(m,k))Z mod Z (the lcm law); and the
CRT surjection Z/mZ x Z/kZ ->> Z/lcm(m,k)Z, (a,b) -> a L/m + b L/k mod L,
has kernel cyclic of order d = gcd(m,k) generated by (m/d, -k/d).

We model relative charges as elements of Q/Z and re-derive each identity.
"""
import math
from fractions import Fraction

import pytest
import sympy as sp

import _relcharge as R

x = R.x


def frac_mod1(a):
    return Fraction(a) % 1


@pytest.mark.parametrize("k", [1, 2, 3, 4, 5, 6])
def test_adams_multiplies_relative_charge_by_k(k):
    """Prop 4.8: t_rel(alpha^k, beta^k) = k t_rel(alpha, beta) in R/Z.

    Realized concretely: for O = x^m - 2 the angles are j/m; psi^k sends
    angle t -> k t mod 1.  Check on the object x^m - 2 that the multiset of
    pairwise differences scales by k and that Delta(psi^k O) = k Delta(O)."""
    m = 6
    ang = [Fraction(j, m) for j in range(m)]
    ang_k = [(k * t) % 1 for t in ang]
    diffs = {(a - b) % 1 for a in ang for b in ang}
    diffs_k = {(a - b) % 1 for a in ang_k for b in ang_k}
    # every psi^k difference is k times an original difference
    assert diffs_k == {(k * d) % 1 for d in diffs}
    # relational order: Delta(psi^k O) = k Delta(O) as subgroups of Q/Z
    def order(diffset):
        L = 1
        for d in diffset:
            L = L * d.denominator // math.gcd(L, d.denominator)
        return L
    m0 = order(diffs)
    mk = order(diffs_k)
    # k * (1/m0 Z/Z) = 1/(m0/gcd(m0,k)) Z/Z
    assert mk == m0 // math.gcd(m0, k)


def test_adams_projects_onto_primary_components():
    """Prop 4.8: for m = prod p_i^{e_i}, psi^{m/p_i^{e_i}} projects Z/mZ onto
    its p_i-primary component Z/p_i^{e_i}Z.  Verify the subgroup generated by
    (m/p_i^{e_i}) * (1/m) has order p_i^{e_i}."""
    m = 12  # = 2^2 * 3
    for pe in [4, 3]:  # the prime-power parts
        k = m // pe
        gen = Fraction(k, m) % 1        # = 1/pe
        # order of gen in Q/Z:
        assert gen.denominator == pe


@pytest.mark.parametrize(
    "m,k",
    [(2, 3), (4, 6), (3, 5), (6, 10), (4, 4), (12, 8), (9, 6), (5, 5)],
)
def test_tensor_lcm_law(m, k):
    """Prop 4.9(ii): (1/m)Z + (1/k)Z = (1/lcm(m,k))Z as subgroups of Q/Z, so
    Delta(A (x) B) = Z/lcm(m,k)Z on admissible inputs."""
    L = sp.ilcm(m, k)
    # subgroup generated by 1/m and 1/k inside Q/Z:
    gens = set()
    for a in range(m):
        gens.add(Fraction(a, m) % 1)
    combined = set()
    for a in range(m):
        for b in range(k):
            combined.add((Fraction(a, m) + Fraction(b, k)) % 1)
    target = {Fraction(j, L) % 1 for j in range(L)}
    assert combined == target
    # order of the sum group is exactly lcm(m,k):
    dens = {f.denominator for f in combined}
    order = 1
    for d in dens:
        order = order * d // math.gcd(order, d)
    assert order == L


@pytest.mark.parametrize(
    "m,k", [(2, 3), (4, 6), (3, 5), (6, 10), (12, 8), (9, 6), (10, 15)]
)
def test_crt_surjection_kernel_is_cyclic_of_order_gcd(m, k):
    """Prop 4.9(ii) proof: the map Z/mZ x Z/kZ -> Z/LZ,
    (a,b) -> a L/m + b L/k mod L (L=lcm), is surjective with kernel cyclic of
    order d = gcd(m,k), generated by (m/d, -k/d)."""
    L = sp.ilcm(m, k)
    d = math.gcd(m, k)

    def surj(a, b):
        return (a * (L // m) + b * (L // k)) % L

    image = {surj(a, b) for a in range(m) for b in range(k)}
    assert image == set(range(L))  # surjective

    kernel = [(a, b) for a in range(m) for b in range(k) if surj(a, b) == 0]
    assert len(kernel) == d  # |kernel| = |domain|/|image| = m k / L = gcd

    # generated by (m/d, -k/d):
    g = (m // d % m, (-(k // d)) % k)
    gen_subgroup = set()
    cur = (0, 0)
    for _ in range(d):
        gen_subgroup.add(cur)
        cur = ((cur[0] + g[0]) % m, (cur[1] + g[1]) % k)
    assert gen_subgroup == set(kernel)


def test_safe_composition_iff_coprime():
    """Prop 4.9(ii): safe composition (factor charges independently
    recoverable) <=> coprime orders.  The CRT map is an isomorphism (kernel
    trivial) exactly when gcd(m,k)=1."""
    for m in range(1, 13):
        for k in range(1, 13):
            L = sp.ilcm(m, k)
            iso = (m * k == L)  # kernel trivial <=> product = lcm <=> coprime
            assert iso == (math.gcd(m, k) == 1)


def test_tensor_containment_via_angles():
    """Prop 4.9(i): a pair (alpha beta, alpha' beta') in A (x) B is coherent iff
    (t(alpha)-t(alpha')) + (t(beta)-t(beta')) is rational; taking beta=beta' or
    alpha=alpha' yields Delta(A (x) B) contains Delta(A) + Delta(B).

    Concrete instance: A = x^3-2 (angles j/3), B = x^4-2 (angles j/4);
    products realize (1/3)Z + (1/4)Z = (1/12)Z."""
    angA = [Fraction(j, 3) for j in range(3)]
    angB = [Fraction(j, 4) for j in range(4)]
    prod_angles = {(a + b) % 1 for a in angA for b in angB}
    diffs = {(u - v) % 1 for u in prod_angles for v in prod_angles}
    order = 1
    for d in diffs:
        order = order * d.denominator // math.gcd(order, d.denominator)
    assert order == 12  # lcm(3,4)
