r"""The cocycle, trivialization and gauge: Proposition 3.8 (prop:gauge) and
Proposition 3.6 (prop:cyclic).

Paper (Prop 3.8):
  (i)   cocycle: t_rel(a,b) + t_rel(b,c) = t_rel(a,c) on coherent triples;
  (ii)  coboundary: on a charge-admissible object with group Z/nZ,
        t_rel(a,b) = (chi_n(a) - chi_n(b)) / n;
  (iii) trivializations differ by a constant;
  (iv)  rotation rho_c: alpha -> e^{2 pi i c} alpha shifts every absolute angle
        by c and fixes every relative charge.

Paper (Prop 3.6): every class group and relational group is a finite cyclic
group Z/mZ (Q/Z has exactly one subgroup of each finite order).

Relative charges are modelled as elements of Q/Z (angles of admissible
objects) and the identities are re-derived exactly.
"""
from fractions import Fraction

import pytest
import sympy as sp

import _relcharge as R

x = R.x


def _angles(p):
    return R.angles_of(p)


@pytest.mark.parametrize(
    "p", [x**3 - 2, x**4 - 2, x**3 + 2, x**4 + 5 * x**2 + 5, x**6 + x**3 - 1]
)
def test_cocycle_identity(p):
    """Prop 3.8(i): for all coherent triples, t_rel(a,b)+t_rel(b,c)=t_rel(a,c)
    in Q/Z (an exact telescoping identity)."""
    ang = _angles(p)
    for a in ang:
        for b in ang:
            for c in ang:
                lhs = ((a - b) + (b - c)) % 1
                rhs = (a - c) % 1
                assert lhs == rhs


@pytest.mark.parametrize("p", [x**3 - 2, x**4 - 2, x**5 - 2, x**4 + 5 * x**2 - 5])
def test_coboundary_of_absolute_charge(p):
    """Prop 3.8(ii): on a charge-admissible object with group Z/nZ,
    t_rel(a,b) = (chi_n(a) - chi_n(b))/n where chi_n(a) = n t(a) mod n."""
    n = R.absolute_lcd(p)
    ang = _angles(p)
    for a in ang:
        for b in ang:
            chi_a = (n * a) % n
            chi_b = (n * b) % n
            trel = (a - b) % 1
            assert (Fraction(chi_a - chi_b, n)) % 1 == trel


@pytest.mark.parametrize("p", [x**3 - 2, x**4 - 2, x**4 + 5 * x**2 + 5])
def test_rotation_fixes_relative_charge(p):
    """Prop 3.8(iv): rho_c shifts every absolute angle by c but fixes every
    relative charge t_rel(a,b) = (a+c) - (b+c)."""
    ang = _angles(p)
    for c in [Fraction(1, 7), Fraction(3, 5), Fraction(2, 11)]:
        shifted = [(a + c) % 1 for a in ang]
        for i in range(len(ang)):
            for j in range(len(ang)):
                assert (shifted[i] - shifted[j]) % 1 == (ang[i] - ang[j]) % 1


@pytest.mark.parametrize("p", [x**3 - 2, x**4 - 2, x**3 + 2, x**6 + x**3 - 1])
def test_trivializations_differ_by_a_constant(p):
    """Prop 3.8(iii): any section s with s(a)-s(b)=t_rel(a,b) differs from the
    absolute angle by a global constant.  Take s(a)=t(a)+k for a fixed k;
    then s(a)-s(b)=t(a)-t(b) for every pair."""
    ang = _angles(p)
    for k in [Fraction(1, 3), Fraction(5, 8)]:
        s = [(a + k) % 1 for a in ang]
        for i in range(len(ang)):
            for j in range(len(ang)):
                assert (s[i] - s[j]) % 1 == (ang[i] - ang[j]) % 1


@pytest.mark.parametrize(
    "p,m",
    [
        (x**3 - 2, 3),
        (x**4 - 2, 4),
        (x**5 - 2, 5),
        (x**4 + 5 * x**2 + 5, 2),
        (x**4 + 5 * x**2 - 5, 4),
        (x**6 + x**3 - 1, 6),  # = q_3, angle set (1/6)Z/Z so Delta = Z/6
        (x**4 + x**2 - 1, 4),
    ],
)
def test_relational_group_is_cyclic_Zm(p, m):
    """Prop 3.6: the relational group is cyclic Z/mZ.  We verify it is exactly
    the group (1/m)Z/Z: the set of pairwise differences equals {j/m} and has
    order m (a single cyclic subgroup of Q/Z of that order)."""
    ang = _angles(p)
    diffs = {((a - b) % 1) for a in ang for b in ang}
    assert R.relational_order(p) == m
    # the difference set is exactly the cyclic group generated by 1/m:
    assert diffs == {Fraction(j, m) for j in range(m)}


def test_no_noncyclic_group_occurs():
    """Prop 3.6: no non-cyclic group occurs.  A finite subgroup of Q/Z is
    determined by its order (one subgroup per order), so it is always cyclic;
    verify the generated difference group is singly generated for a batch of
    admissible objects (its size equals the order of 1/den_lcm)."""
    for p in [x**3 - 2, x**4 - 2, x**6 - 2, x**4 + 5 * x**2 + 5, x**4 + x**2 - 1]:
        m = R.relational_order(p)
        diffs = {((a - b) % 1) for a in R.angles_of(p) for b in R.angles_of(p)}
        # cyclic of order m <=> exactly m elements, all multiples of 1/m
        assert len(diffs) == m
        assert all((d * m) % 1 == 0 for d in diffs)
