"""
Independent verification of the group-theoretic backbone (Sec 3):
  * Cyclicity of charge groups (Thm 3.1) -- every finite subgroup of Q/Z is cyclic.
  * CRT / Adams primary decomposition (Thm 3.4).
  * The lcm law under tensor (Thm 3.5).
  * Safe composition <=> coprime orders (Thm 3.7).

These are exact finite-group computations in Z/L (no floating point).
"""

from math import gcd
from functools import reduce
import sympy as sp


def _lcm(a, b):
    return a * b // gcd(a, b)


def _subgroup(gens, L):
    """Closure under addition of {gens} inside Z/L (contains 0)."""
    S = {0}
    frontier = {g % L for g in gens} | {0}
    while frontier:
        new = set()
        for s in list(S):
            for g in frontier:
                v = (s + g) % L
                if v not in S:
                    new.add(v)
        if not new:
            break
        S |= new
    # ensure full closure
    changed = True
    while changed:
        changed = False
        for a in list(S):
            for g in {x % L for x in gens}:
                v = (a + g) % L
                if v not in S:
                    S.add(v)
                    changed = True
    return S


# --------------------------------------------------------------------------
# Cyclicity of charge groups  (Thm 3.1)
# --------------------------------------------------------------------------
def test_subgroup_of_ZmodL_is_cyclic():
    """Thm 3.1: every finite subgroup of Q/Z is cyclic.  Concretely, a charge
    set with common denominator L generates a subgroup of Z/L that equals
    <gcd(residues, L)> -- hence cyclic, of order L/gcd."""
    for L in range(2, 25):
        for gens in ([1], [2, 3], [4, 6], [L - 1], [0], [3, 6, 9]):
            g = reduce(gcd, [x % L for x in gens] + [L])
            S = _subgroup(gens, L)
            expected = {(g * j) % L for j in range(L // g)}
            assert S == expected                       # cyclic, generated by g
            assert len(S) == L // g


def test_ZpxZp_is_not_cyclic():
    """Thm 3.1 corollary: Z/p x Z/p is unrealizable as a charge group because
    it is NOT cyclic (exponent p, no element of order p^2)."""
    for p in (2, 3, 5):
        orders = []
        for a in range(p):
            for b in range(p):
                # order of (a,b) in Z/p x Z/p
                o = 1
                while (a * o) % p != 0 or (b * o) % p != 0:
                    o += 1
                orders.append(o)
        assert max(orders) == p                        # exponent p < p^2 = |G|
        assert p * p > p                               # so G is non-cyclic


# --------------------------------------------------------------------------
# CRT / Adams primary decomposition  (Thm 3.4)
# --------------------------------------------------------------------------
def test_crt_isomorphism_and_adams_projectors():
    """Thm 3.4: for n = prod p_i^{e_i}, Z/n = prod Z/p_i^{e_i} (CRT), and
    multiplication by k = n/p_i^{e_i} (the Adams operator psi^k on charges) has
    image = unique order-p_i^{e_i} subgroup and kernel = complementary factor."""
    for n in (6, 12, 30, 36, 60):
        fac = sp.factorint(n)
        # CRT bijection Z/n -> prod Z/p^e
        images = set()
        for a in range(n):
            images.add(tuple(a % (p**e) for p, e in fac.items()))
        assert len(images) == n                        # bijection => isomorphism
        # Adams projectors
        for p, e in fac.items():
            pe = p**e
            k = n // pe
            img = {(k * a) % n for a in range(n)}
            ker = {a for a in range(n) if (k * a) % n == 0}
            assert len(img) == pe                       # image is order p^e
            assert len(ker) == n // pe                  # kernel is complement
            # image is exactly the unique subgroup of order pe
            assert img == {(n // pe) * j % n for j in range(pe)}


# --------------------------------------------------------------------------
# lcm law  (Thm 3.5)
# --------------------------------------------------------------------------
def test_lcm_law_subgroup_order():
    """Thm 3.5: (1/m)Z + (1/k)Z = (1/lcm)Z in Q/Z; the tensor charge group has
    order lcm(m,k).  Verified by generating <L/m, L/k> in Z/L (L=lcm)."""
    for m in range(1, 13):
        for k in range(1, 13):
            L = _lcm(m, k)
            S = _subgroup([L // m, L // k], L)
            assert len(S) == L                          # full Z/lcm
            assert L == _lcm(m, k)


# --------------------------------------------------------------------------
# Safe composition <=> coprime  (Thm 3.7)
# --------------------------------------------------------------------------
def test_safe_composition_iff_coprime():
    """Thm 3.7: the surjection Z/m x Z/k ->> Z/lcm(m,k) is lossless (trivial
    kernel) iff gcd(m,k)=1.  Kernel order = mk/lcm = gcd(m,k)."""
    for m in range(1, 16):
        for k in range(1, 16):
            L = _lcm(m, k)
            kernel_order = (m * k) // L
            assert kernel_order == gcd(m, k)
            lossless = (kernel_order == 1)
            assert lossless == (gcd(m, k) == 1)
            assert (L == m * k) == (gcd(m, k) == 1)
